/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketMinipoolBondReducerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "beginReduceBondAmount"
      | "canReduceBondAmount"
      | "getLastBondReductionPrevNodeFee"
      | "getLastBondReductionPrevValue"
      | "getLastBondReductionTime"
      | "getReduceBondCancelled"
      | "getReduceBondTime"
      | "getReduceBondValue"
      | "reduceBondAmount"
      | "version"
      | "voteCancelReduction"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CancelReductionVoted" | "ReductionCancelled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "beginReduceBondAmount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canReduceBondAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastBondReductionPrevNodeFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastBondReductionPrevValue",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastBondReductionTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReduceBondCancelled",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReduceBondTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReduceBondValue",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reduceBondAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "voteCancelReduction",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "beginReduceBondAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canReduceBondAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastBondReductionPrevNodeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastBondReductionPrevValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastBondReductionTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReduceBondCancelled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReduceBondTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReduceBondValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reduceBondAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteCancelReduction",
    data: BytesLike
  ): Result;
}

export namespace CancelReductionVotedEvent {
  export type InputTuple = [
    minipool: AddressLike,
    member: AddressLike,
    time: BigNumberish
  ];
  export type OutputTuple = [minipool: string, member: string, time: bigint];
  export interface OutputObject {
    minipool: string;
    member: string;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReductionCancelledEvent {
  export type InputTuple = [minipool: AddressLike, time: BigNumberish];
  export type OutputTuple = [minipool: string, time: bigint];
  export interface OutputObject {
    minipool: string;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RocketMinipoolBondReducer extends BaseContract {
  connect(runner?: ContractRunner | null): RocketMinipoolBondReducer;
  waitForDeployment(): Promise<this>;

  interface: RocketMinipoolBondReducerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  beginReduceBondAmount: TypedContractMethod<
    [_minipoolAddress: AddressLike, _newBondAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  canReduceBondAmount: TypedContractMethod<
    [_minipoolAddress: AddressLike],
    [boolean],
    "view"
  >;

  getLastBondReductionPrevNodeFee: TypedContractMethod<
    [_minipoolAddress: AddressLike],
    [bigint],
    "view"
  >;

  getLastBondReductionPrevValue: TypedContractMethod<
    [_minipoolAddress: AddressLike],
    [bigint],
    "view"
  >;

  getLastBondReductionTime: TypedContractMethod<
    [_minipoolAddress: AddressLike],
    [bigint],
    "view"
  >;

  getReduceBondCancelled: TypedContractMethod<
    [_minipoolAddress: AddressLike],
    [boolean],
    "view"
  >;

  getReduceBondTime: TypedContractMethod<
    [_minipoolAddress: AddressLike],
    [bigint],
    "view"
  >;

  getReduceBondValue: TypedContractMethod<
    [_minipoolAddress: AddressLike],
    [bigint],
    "view"
  >;

  reduceBondAmount: TypedContractMethod<[], [bigint], "nonpayable">;

  version: TypedContractMethod<[], [bigint], "view">;

  voteCancelReduction: TypedContractMethod<
    [_minipoolAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "beginReduceBondAmount"
  ): TypedContractMethod<
    [_minipoolAddress: AddressLike, _newBondAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canReduceBondAmount"
  ): TypedContractMethod<[_minipoolAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getLastBondReductionPrevNodeFee"
  ): TypedContractMethod<[_minipoolAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLastBondReductionPrevValue"
  ): TypedContractMethod<[_minipoolAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLastBondReductionTime"
  ): TypedContractMethod<[_minipoolAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReduceBondCancelled"
  ): TypedContractMethod<[_minipoolAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getReduceBondTime"
  ): TypedContractMethod<[_minipoolAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReduceBondValue"
  ): TypedContractMethod<[_minipoolAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "reduceBondAmount"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "voteCancelReduction"
  ): TypedContractMethod<[_minipoolAddress: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CancelReductionVoted"
  ): TypedContractEvent<
    CancelReductionVotedEvent.InputTuple,
    CancelReductionVotedEvent.OutputTuple,
    CancelReductionVotedEvent.OutputObject
  >;
  getEvent(
    key: "ReductionCancelled"
  ): TypedContractEvent<
    ReductionCancelledEvent.InputTuple,
    ReductionCancelledEvent.OutputTuple,
    ReductionCancelledEvent.OutputObject
  >;

  filters: {
    "CancelReductionVoted(address,address,uint256)": TypedContractEvent<
      CancelReductionVotedEvent.InputTuple,
      CancelReductionVotedEvent.OutputTuple,
      CancelReductionVotedEvent.OutputObject
    >;
    CancelReductionVoted: TypedContractEvent<
      CancelReductionVotedEvent.InputTuple,
      CancelReductionVotedEvent.OutputTuple,
      CancelReductionVotedEvent.OutputObject
    >;

    "ReductionCancelled(address,uint256)": TypedContractEvent<
      ReductionCancelledEvent.InputTuple,
      ReductionCancelledEvent.OutputTuple,
      ReductionCancelledEvent.OutputObject
    >;
    ReductionCancelled: TypedContractEvent<
      ReductionCancelledEvent.InputTuple,
      ReductionCancelledEvent.OutputTuple,
      ReductionCancelledEvent.OutputObject
    >;
  };
}
