/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketNodeStakingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "burnRPL"
      | "getNodeETHBonded"
      | "getNodeETHBorrowed"
      | "getNodeETHCollateralisationRatio"
      | "getNodeLastUnstakeTime"
      | "getNodeLegacyStakedRPL"
      | "getNodeLockedRPL"
      | "getNodeMegapoolETHBonded"
      | "getNodeMegapoolETHBorrowed"
      | "getNodeMegapoolStakedRPL"
      | "getNodeMinimumLegacyRPLStake"
      | "getNodeMinipoolETHBonded"
      | "getNodeMinipoolETHBorrowed"
      | "getNodeRPLStakedTime"
      | "getNodeStakedRPL"
      | "getNodeUnstakingRPL"
      | "getRPLLockingAllowed"
      | "getTotalLegacyStakedRPL"
      | "getTotalMegapoolStakedRPL"
      | "getTotalStakedRPL"
      | "lockRPL"
      | "setRPLLockingAllowed"
      | "setStakeRPLForAllowed(address,bool)"
      | "setStakeRPLForAllowed(address,address,bool)"
      | "slashRPL"
      | "stakeRPL"
      | "stakeRPLFor"
      | "transferRPL"
      | "unlockRPL"
      | "unstakeLegacyRPL"
      | "unstakeLegacyRPLFor"
      | "unstakeRPL"
      | "unstakeRPLFor"
      | "version"
      | "withdrawRPL"
      | "withdrawRPLFor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RPLBurned"
      | "RPLLegacyUnstaked"
      | "RPLLocked"
      | "RPLLockingAllowed"
      | "RPLSlashed"
      | "RPLStaked(address,address,uint256,uint256)"
      | "RPLStaked(address,uint256,uint256)"
      | "RPLTransferred"
      | "RPLUnlocked"
      | "RPLUnstaked"
      | "RPLWithdrawn"
      | "StakeRPLForAllowed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "burnRPL",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeETHBonded",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeETHBorrowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeETHCollateralisationRatio",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeLastUnstakeTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeLegacyStakedRPL",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeLockedRPL",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeMegapoolETHBonded",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeMegapoolETHBorrowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeMegapoolStakedRPL",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeMinimumLegacyRPLStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeMinipoolETHBonded",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeMinipoolETHBorrowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeRPLStakedTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeStakedRPL",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeUnstakingRPL",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRPLLockingAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalLegacyStakedRPL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalMegapoolStakedRPL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalStakedRPL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockRPL",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRPLLockingAllowed",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakeRPLForAllowed(address,bool)",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakeRPLForAllowed(address,address,bool)",
    values: [AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "slashRPL",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeRPL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeRPLFor",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferRPL",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockRPL",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeLegacyRPL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeLegacyRPLFor",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeRPL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeRPLFor",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawRPL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRPLFor",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "burnRPL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNodeETHBonded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeETHBorrowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeETHCollateralisationRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeLastUnstakeTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeLegacyStakedRPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeLockedRPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeMegapoolETHBonded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeMegapoolETHBorrowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeMegapoolStakedRPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeMinimumLegacyRPLStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeMinipoolETHBonded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeMinipoolETHBorrowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeRPLStakedTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeStakedRPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeUnstakingRPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRPLLockingAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalLegacyStakedRPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalMegapoolStakedRPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalStakedRPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockRPL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRPLLockingAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakeRPLForAllowed(address,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakeRPLForAllowed(address,address,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slashRPL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeRPL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeRPLFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferRPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlockRPL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unstakeLegacyRPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeLegacyRPLFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstakeRPL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unstakeRPLFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRPLFor",
    data: BytesLike
  ): Result;
}

export namespace RPLBurnedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [from: string, amount: bigint, time: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLLegacyUnstakedEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [to: string, amount: bigint, time: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLLockedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [from: string, amount: bigint, time: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLLockingAllowedEvent {
  export type InputTuple = [
    node: AddressLike,
    allowed: boolean,
    time: BigNumberish
  ];
  export type OutputTuple = [node: string, allowed: boolean, time: bigint];
  export interface OutputObject {
    node: string;
    allowed: boolean;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLSlashedEvent {
  export type InputTuple = [
    node: AddressLike,
    amount: BigNumberish,
    ethValue: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [
    node: string,
    amount: bigint,
    ethValue: bigint,
    time: bigint
  ];
  export interface OutputObject {
    node: string;
    amount: bigint;
    ethValue: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLStaked_address_address_uint256_uint256_Event {
  export type InputTuple = [
    node: AddressLike,
    from: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [
    node: string,
    from: string,
    amount: bigint,
    time: bigint
  ];
  export interface OutputObject {
    node: string;
    from: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLStaked_address_uint256_uint256_Event {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [from: string, amount: bigint, time: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLTransferredEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    time: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLUnlockedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [from: string, amount: bigint, time: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLUnstakedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [from: string, amount: bigint, time: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLWithdrawnEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [to: string, amount: bigint, time: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeRPLForAllowedEvent {
  export type InputTuple = [
    node: AddressLike,
    caller: AddressLike,
    allowed: boolean,
    time: BigNumberish
  ];
  export type OutputTuple = [
    node: string,
    caller: string,
    allowed: boolean,
    time: bigint
  ];
  export interface OutputObject {
    node: string;
    caller: string;
    allowed: boolean;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RocketNodeStaking extends BaseContract {
  connect(runner?: ContractRunner | null): RocketNodeStaking;
  waitForDeployment(): Promise<this>;

  interface: RocketNodeStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  burnRPL: TypedContractMethod<
    [_from: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getNodeETHBonded: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeETHBorrowed: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeETHCollateralisationRatio: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeLastUnstakeTime: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeLegacyStakedRPL: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeLockedRPL: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeMegapoolETHBonded: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeMegapoolETHBorrowed: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeMegapoolStakedRPL: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeMinimumLegacyRPLStake: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeMinipoolETHBonded: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeMinipoolETHBorrowed: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeRPLStakedTime: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeStakedRPL: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeUnstakingRPL: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getRPLLockingAllowed: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [boolean],
    "view"
  >;

  getTotalLegacyStakedRPL: TypedContractMethod<[], [bigint], "view">;

  getTotalMegapoolStakedRPL: TypedContractMethod<[], [bigint], "view">;

  getTotalStakedRPL: TypedContractMethod<[], [bigint], "view">;

  lockRPL: TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRPLLockingAllowed: TypedContractMethod<
    [_nodeAddress: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;

  "setStakeRPLForAllowed(address,bool)": TypedContractMethod<
    [_caller: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;

  "setStakeRPLForAllowed(address,address,bool)": TypedContractMethod<
    [_nodeAddress: AddressLike, _caller: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;

  slashRPL: TypedContractMethod<
    [_nodeAddress: AddressLike, _ethSlashAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeRPL: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  stakeRPLFor: TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferRPL: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unlockRPL: TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unstakeLegacyRPL: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unstakeLegacyRPLFor: TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unstakeRPL: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unstakeRPLFor: TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  withdrawRPL: TypedContractMethod<[], [void], "nonpayable">;

  withdrawRPLFor: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "burnRPL"
  ): TypedContractMethod<
    [_from: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getNodeETHBonded"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeETHBorrowed"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeETHCollateralisationRatio"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeLastUnstakeTime"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeLegacyStakedRPL"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeLockedRPL"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeMegapoolETHBonded"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeMegapoolETHBorrowed"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeMegapoolStakedRPL"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeMinimumLegacyRPLStake"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeMinipoolETHBonded"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeMinipoolETHBorrowed"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeRPLStakedTime"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeStakedRPL"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeUnstakingRPL"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRPLLockingAllowed"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getTotalLegacyStakedRPL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalMegapoolStakedRPL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalStakedRPL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockRPL"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRPLLockingAllowed"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStakeRPLForAllowed(address,bool)"
  ): TypedContractMethod<
    [_caller: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStakeRPLForAllowed(address,address,bool)"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _caller: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slashRPL"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _ethSlashAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeRPL"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeRPLFor"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferRPL"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockRPL"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unstakeLegacyRPL"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeLegacyRPLFor"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unstakeRPL"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeRPLFor"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawRPL"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawRPLFor"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "RPLBurned"
  ): TypedContractEvent<
    RPLBurnedEvent.InputTuple,
    RPLBurnedEvent.OutputTuple,
    RPLBurnedEvent.OutputObject
  >;
  getEvent(
    key: "RPLLegacyUnstaked"
  ): TypedContractEvent<
    RPLLegacyUnstakedEvent.InputTuple,
    RPLLegacyUnstakedEvent.OutputTuple,
    RPLLegacyUnstakedEvent.OutputObject
  >;
  getEvent(
    key: "RPLLocked"
  ): TypedContractEvent<
    RPLLockedEvent.InputTuple,
    RPLLockedEvent.OutputTuple,
    RPLLockedEvent.OutputObject
  >;
  getEvent(
    key: "RPLLockingAllowed"
  ): TypedContractEvent<
    RPLLockingAllowedEvent.InputTuple,
    RPLLockingAllowedEvent.OutputTuple,
    RPLLockingAllowedEvent.OutputObject
  >;
  getEvent(
    key: "RPLSlashed"
  ): TypedContractEvent<
    RPLSlashedEvent.InputTuple,
    RPLSlashedEvent.OutputTuple,
    RPLSlashedEvent.OutputObject
  >;
  getEvent(
    key: "RPLStaked(address,address,uint256,uint256)"
  ): TypedContractEvent<
    RPLStaked_address_address_uint256_uint256_Event.InputTuple,
    RPLStaked_address_address_uint256_uint256_Event.OutputTuple,
    RPLStaked_address_address_uint256_uint256_Event.OutputObject
  >;
  getEvent(
    key: "RPLStaked(address,uint256,uint256)"
  ): TypedContractEvent<
    RPLStaked_address_uint256_uint256_Event.InputTuple,
    RPLStaked_address_uint256_uint256_Event.OutputTuple,
    RPLStaked_address_uint256_uint256_Event.OutputObject
  >;
  getEvent(
    key: "RPLTransferred"
  ): TypedContractEvent<
    RPLTransferredEvent.InputTuple,
    RPLTransferredEvent.OutputTuple,
    RPLTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RPLUnlocked"
  ): TypedContractEvent<
    RPLUnlockedEvent.InputTuple,
    RPLUnlockedEvent.OutputTuple,
    RPLUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "RPLUnstaked"
  ): TypedContractEvent<
    RPLUnstakedEvent.InputTuple,
    RPLUnstakedEvent.OutputTuple,
    RPLUnstakedEvent.OutputObject
  >;
  getEvent(
    key: "RPLWithdrawn"
  ): TypedContractEvent<
    RPLWithdrawnEvent.InputTuple,
    RPLWithdrawnEvent.OutputTuple,
    RPLWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "StakeRPLForAllowed"
  ): TypedContractEvent<
    StakeRPLForAllowedEvent.InputTuple,
    StakeRPLForAllowedEvent.OutputTuple,
    StakeRPLForAllowedEvent.OutputObject
  >;

  filters: {
    "RPLBurned(address,uint256,uint256)": TypedContractEvent<
      RPLBurnedEvent.InputTuple,
      RPLBurnedEvent.OutputTuple,
      RPLBurnedEvent.OutputObject
    >;
    RPLBurned: TypedContractEvent<
      RPLBurnedEvent.InputTuple,
      RPLBurnedEvent.OutputTuple,
      RPLBurnedEvent.OutputObject
    >;

    "RPLLegacyUnstaked(address,uint256,uint256)": TypedContractEvent<
      RPLLegacyUnstakedEvent.InputTuple,
      RPLLegacyUnstakedEvent.OutputTuple,
      RPLLegacyUnstakedEvent.OutputObject
    >;
    RPLLegacyUnstaked: TypedContractEvent<
      RPLLegacyUnstakedEvent.InputTuple,
      RPLLegacyUnstakedEvent.OutputTuple,
      RPLLegacyUnstakedEvent.OutputObject
    >;

    "RPLLocked(address,uint256,uint256)": TypedContractEvent<
      RPLLockedEvent.InputTuple,
      RPLLockedEvent.OutputTuple,
      RPLLockedEvent.OutputObject
    >;
    RPLLocked: TypedContractEvent<
      RPLLockedEvent.InputTuple,
      RPLLockedEvent.OutputTuple,
      RPLLockedEvent.OutputObject
    >;

    "RPLLockingAllowed(address,bool,uint256)": TypedContractEvent<
      RPLLockingAllowedEvent.InputTuple,
      RPLLockingAllowedEvent.OutputTuple,
      RPLLockingAllowedEvent.OutputObject
    >;
    RPLLockingAllowed: TypedContractEvent<
      RPLLockingAllowedEvent.InputTuple,
      RPLLockingAllowedEvent.OutputTuple,
      RPLLockingAllowedEvent.OutputObject
    >;

    "RPLSlashed(address,uint256,uint256,uint256)": TypedContractEvent<
      RPLSlashedEvent.InputTuple,
      RPLSlashedEvent.OutputTuple,
      RPLSlashedEvent.OutputObject
    >;
    RPLSlashed: TypedContractEvent<
      RPLSlashedEvent.InputTuple,
      RPLSlashedEvent.OutputTuple,
      RPLSlashedEvent.OutputObject
    >;

    "RPLStaked(address,address,uint256,uint256)": TypedContractEvent<
      RPLStaked_address_address_uint256_uint256_Event.InputTuple,
      RPLStaked_address_address_uint256_uint256_Event.OutputTuple,
      RPLStaked_address_address_uint256_uint256_Event.OutputObject
    >;
    "RPLStaked(address,uint256,uint256)": TypedContractEvent<
      RPLStaked_address_uint256_uint256_Event.InputTuple,
      RPLStaked_address_uint256_uint256_Event.OutputTuple,
      RPLStaked_address_uint256_uint256_Event.OutputObject
    >;

    "RPLTransferred(address,address,uint256,uint256)": TypedContractEvent<
      RPLTransferredEvent.InputTuple,
      RPLTransferredEvent.OutputTuple,
      RPLTransferredEvent.OutputObject
    >;
    RPLTransferred: TypedContractEvent<
      RPLTransferredEvent.InputTuple,
      RPLTransferredEvent.OutputTuple,
      RPLTransferredEvent.OutputObject
    >;

    "RPLUnlocked(address,uint256,uint256)": TypedContractEvent<
      RPLUnlockedEvent.InputTuple,
      RPLUnlockedEvent.OutputTuple,
      RPLUnlockedEvent.OutputObject
    >;
    RPLUnlocked: TypedContractEvent<
      RPLUnlockedEvent.InputTuple,
      RPLUnlockedEvent.OutputTuple,
      RPLUnlockedEvent.OutputObject
    >;

    "RPLUnstaked(address,uint256,uint256)": TypedContractEvent<
      RPLUnstakedEvent.InputTuple,
      RPLUnstakedEvent.OutputTuple,
      RPLUnstakedEvent.OutputObject
    >;
    RPLUnstaked: TypedContractEvent<
      RPLUnstakedEvent.InputTuple,
      RPLUnstakedEvent.OutputTuple,
      RPLUnstakedEvent.OutputObject
    >;

    "RPLWithdrawn(address,uint256,uint256)": TypedContractEvent<
      RPLWithdrawnEvent.InputTuple,
      RPLWithdrawnEvent.OutputTuple,
      RPLWithdrawnEvent.OutputObject
    >;
    RPLWithdrawn: TypedContractEvent<
      RPLWithdrawnEvent.InputTuple,
      RPLWithdrawnEvent.OutputTuple,
      RPLWithdrawnEvent.OutputObject
    >;

    "StakeRPLForAllowed(address,address,bool,uint256)": TypedContractEvent<
      StakeRPLForAllowedEvent.InputTuple,
      StakeRPLForAllowedEvent.OutputTuple,
      StakeRPLForAllowedEvent.OutputObject
    >;
    StakeRPLForAllowed: TypedContractEvent<
      StakeRPLForAllowedEvent.InputTuple,
      StakeRPLForAllowedEvent.OutputTuple,
      StakeRPLForAllowedEvent.OutputObject
    >;
  };
}
