/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketUpgradeOneDotFourInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "abisA"
      | "abisB"
      | "addressesA"
      | "addressesB"
      | "execute"
      | "getRocketStorageAddress"
      | "lockedA"
      | "lockedB"
      | "setA"
      | "setB"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "abisA", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "abisB", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "addressesA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addressesB",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "execute", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRocketStorageAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lockedA", values?: undefined): string;
  encodeFunctionData(functionFragment: "lockedB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setA",
    values: [AddressLike[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setB",
    values: [AddressLike[], string[]]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "abisA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "abisB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addressesA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addressesB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRocketStorageAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockedA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockedB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export interface RocketUpgradeOneDotFour extends BaseContract {
  connect(runner?: ContractRunner | null): RocketUpgradeOneDotFour;
  waitForDeployment(): Promise<this>;

  interface: RocketUpgradeOneDotFourInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  abisA: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  abisB: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  addressesA: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  addressesB: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  execute: TypedContractMethod<[], [void], "nonpayable">;

  getRocketStorageAddress: TypedContractMethod<[], [string], "view">;

  lockedA: TypedContractMethod<[], [boolean], "view">;

  lockedB: TypedContractMethod<[], [boolean], "view">;

  setA: TypedContractMethod<
    [_addressesA: AddressLike[], _abisA: string[]],
    [void],
    "nonpayable"
  >;

  setB: TypedContractMethod<
    [_addressesB: AddressLike[], _abisB: string[]],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "abisA"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "abisB"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "addressesA"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "addressesB"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRocketStorageAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lockedA"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockedB"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setA"
  ): TypedContractMethod<
    [_addressesA: AddressLike[], _abisA: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setB"
  ): TypedContractMethod<
    [_addressesB: AddressLike[], _abisB: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
