/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketDAOProtocolSettingsNodeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getBaseBondArray"
      | "getDepositEnabled"
      | "getMaximumStakeForVotingPower"
      | "getMinimumLegacyRPLStake"
      | "getReducedBond"
      | "getRegistrationEnabled"
      | "getSettingAddress"
      | "getSettingAddressList"
      | "getSettingBool"
      | "getSettingUint"
      | "getSmoothingPoolRegistrationEnabled"
      | "getUnstakingPeriod"
      | "getVacantMinipoolsEnabled"
      | "getWithdrawalCooldown"
      | "setSettingAddress"
      | "setSettingAddressList"
      | "setSettingBool"
      | "setSettingUint"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getBaseBondArray",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaximumStakeForVotingPower",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMinimumLegacyRPLStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReducedBond",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistrationEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSettingAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSettingAddressList",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSettingBool",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSettingUint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSmoothingPoolRegistrationEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUnstakingPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVacantMinipoolsEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawalCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSettingAddress",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettingAddressList",
    values: [string, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettingBool",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettingUint",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getBaseBondArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaximumStakeForVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinimumLegacyRPLStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReducedBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistrationEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettingAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettingAddressList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettingBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettingUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSmoothingPoolRegistrationEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnstakingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVacantMinipoolsEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawalCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettingAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettingAddressList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettingBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettingUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export interface RocketDAOProtocolSettingsNode extends BaseContract {
  connect(runner?: ContractRunner | null): RocketDAOProtocolSettingsNode;
  waitForDeployment(): Promise<this>;

  interface: RocketDAOProtocolSettingsNodeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBaseBondArray: TypedContractMethod<[], [bigint[]], "view">;

  getDepositEnabled: TypedContractMethod<[], [boolean], "view">;

  getMaximumStakeForVotingPower: TypedContractMethod<[], [bigint], "view">;

  getMinimumLegacyRPLStake: TypedContractMethod<[], [bigint], "view">;

  getReducedBond: TypedContractMethod<[], [bigint], "view">;

  getRegistrationEnabled: TypedContractMethod<[], [boolean], "view">;

  getSettingAddress: TypedContractMethod<
    [_settingPath: string],
    [string],
    "view"
  >;

  getSettingAddressList: TypedContractMethod<
    [_settingPath: string],
    [string[]],
    "view"
  >;

  getSettingBool: TypedContractMethod<
    [_settingPath: string],
    [boolean],
    "view"
  >;

  getSettingUint: TypedContractMethod<[_settingPath: string], [bigint], "view">;

  getSmoothingPoolRegistrationEnabled: TypedContractMethod<
    [],
    [boolean],
    "view"
  >;

  getUnstakingPeriod: TypedContractMethod<[], [bigint], "view">;

  getVacantMinipoolsEnabled: TypedContractMethod<[], [boolean], "view">;

  getWithdrawalCooldown: TypedContractMethod<[], [bigint], "view">;

  setSettingAddress: TypedContractMethod<
    [_settingPath: string, _value: AddressLike],
    [void],
    "nonpayable"
  >;

  setSettingAddressList: TypedContractMethod<
    [_settingPath: string, _value: AddressLike[]],
    [void],
    "nonpayable"
  >;

  setSettingBool: TypedContractMethod<
    [_settingPath: string, _value: boolean],
    [void],
    "nonpayable"
  >;

  setSettingUint: TypedContractMethod<
    [_settingPath: string, _value: BigNumberish],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBaseBondArray"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDepositEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getMaximumStakeForVotingPower"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMinimumLegacyRPLStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReducedBond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRegistrationEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getSettingAddress"
  ): TypedContractMethod<[_settingPath: string], [string], "view">;
  getFunction(
    nameOrSignature: "getSettingAddressList"
  ): TypedContractMethod<[_settingPath: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSettingBool"
  ): TypedContractMethod<[_settingPath: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "getSettingUint"
  ): TypedContractMethod<[_settingPath: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSmoothingPoolRegistrationEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getUnstakingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVacantMinipoolsEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getWithdrawalCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setSettingAddress"
  ): TypedContractMethod<
    [_settingPath: string, _value: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettingAddressList"
  ): TypedContractMethod<
    [_settingPath: string, _value: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettingBool"
  ): TypedContractMethod<
    [_settingPath: string, _value: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettingUint"
  ): TypedContractMethod<
    [_settingPath: string, _value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
