/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketDAOProtocolSettingsRewardsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRewardsClaimIntervalPeriods"
      | "getRewardsClaimIntervalTime"
      | "getRewardsClaimerPerc"
      | "getRewardsClaimersNodePerc"
      | "getRewardsClaimersPerc"
      | "getRewardsClaimersProtocolPerc"
      | "getRewardsClaimersTimeUpdated"
      | "getRewardsClaimersTrustedNodePerc"
      | "getSettingAddress"
      | "getSettingAddressList"
      | "getSettingBool"
      | "getSettingUint"
      | "setSettingAddress"
      | "setSettingAddressList"
      | "setSettingBool"
      | "setSettingRewardsClaimers"
      | "setSettingUint"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getRewardsClaimIntervalPeriods",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardsClaimIntervalTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardsClaimerPerc",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardsClaimersNodePerc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardsClaimersPerc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardsClaimersProtocolPerc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardsClaimersTimeUpdated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardsClaimersTrustedNodePerc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSettingAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSettingAddressList",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSettingBool",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSettingUint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettingAddress",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettingAddressList",
    values: [string, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettingBool",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettingRewardsClaimers",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettingUint",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getRewardsClaimIntervalPeriods",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardsClaimIntervalTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardsClaimerPerc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardsClaimersNodePerc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardsClaimersPerc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardsClaimersProtocolPerc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardsClaimersTimeUpdated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardsClaimersTrustedNodePerc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettingAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettingAddressList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettingBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettingUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettingAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettingAddressList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettingBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettingRewardsClaimers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettingUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export interface RocketDAOProtocolSettingsRewards extends BaseContract {
  connect(runner?: ContractRunner | null): RocketDAOProtocolSettingsRewards;
  waitForDeployment(): Promise<this>;

  interface: RocketDAOProtocolSettingsRewardsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRewardsClaimIntervalPeriods: TypedContractMethod<[], [bigint], "view">;

  getRewardsClaimIntervalTime: TypedContractMethod<[], [bigint], "view">;

  getRewardsClaimerPerc: TypedContractMethod<
    [_contractName: string],
    [bigint],
    "view"
  >;

  getRewardsClaimersNodePerc: TypedContractMethod<[], [bigint], "view">;

  getRewardsClaimersPerc: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        trustedNodePerc: bigint;
        protocolPerc: bigint;
        nodePerc: bigint;
      }
    ],
    "view"
  >;

  getRewardsClaimersProtocolPerc: TypedContractMethod<[], [bigint], "view">;

  getRewardsClaimersTimeUpdated: TypedContractMethod<[], [bigint], "view">;

  getRewardsClaimersTrustedNodePerc: TypedContractMethod<[], [bigint], "view">;

  getSettingAddress: TypedContractMethod<
    [_settingPath: string],
    [string],
    "view"
  >;

  getSettingAddressList: TypedContractMethod<
    [_settingPath: string],
    [string[]],
    "view"
  >;

  getSettingBool: TypedContractMethod<
    [_settingPath: string],
    [boolean],
    "view"
  >;

  getSettingUint: TypedContractMethod<[_settingPath: string], [bigint], "view">;

  setSettingAddress: TypedContractMethod<
    [_settingPath: string, _value: AddressLike],
    [void],
    "nonpayable"
  >;

  setSettingAddressList: TypedContractMethod<
    [_settingPath: string, _value: AddressLike[]],
    [void],
    "nonpayable"
  >;

  setSettingBool: TypedContractMethod<
    [_settingPath: string, _value: boolean],
    [void],
    "nonpayable"
  >;

  setSettingRewardsClaimers: TypedContractMethod<
    [
      _trustedNodePercent: BigNumberish,
      _protocolPercent: BigNumberish,
      _nodePercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setSettingUint: TypedContractMethod<
    [_settingPath: string, _value: BigNumberish],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRewardsClaimIntervalPeriods"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRewardsClaimIntervalTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRewardsClaimerPerc"
  ): TypedContractMethod<[_contractName: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRewardsClaimersNodePerc"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRewardsClaimersPerc"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        trustedNodePerc: bigint;
        protocolPerc: bigint;
        nodePerc: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRewardsClaimersProtocolPerc"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRewardsClaimersTimeUpdated"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRewardsClaimersTrustedNodePerc"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSettingAddress"
  ): TypedContractMethod<[_settingPath: string], [string], "view">;
  getFunction(
    nameOrSignature: "getSettingAddressList"
  ): TypedContractMethod<[_settingPath: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSettingBool"
  ): TypedContractMethod<[_settingPath: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "getSettingUint"
  ): TypedContractMethod<[_settingPath: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "setSettingAddress"
  ): TypedContractMethod<
    [_settingPath: string, _value: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettingAddressList"
  ): TypedContractMethod<
    [_settingPath: string, _value: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettingBool"
  ): TypedContractMethod<
    [_settingPath: string, _value: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettingRewardsClaimers"
  ): TypedContractMethod<
    [
      _trustedNodePercent: BigNumberish,
      _protocolPercent: BigNumberish,
      _nodePercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettingUint"
  ): TypedContractMethod<
    [_settingPath: string, _value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
