/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace RocketMegapoolStorageLayout {
  export type ValidatorInfoStruct = {
    lastAssignmentTime: BigNumberish;
    lastRequestedValue: BigNumberish;
    lastRequestedBond: BigNumberish;
    depositValue: BigNumberish;
    staked: boolean;
    exited: boolean;
    inQueue: boolean;
    inPrestake: boolean;
    expressUsed: boolean;
    dissolved: boolean;
    exiting: boolean;
    locked: boolean;
    exitBalance: BigNumberish;
    lockedTime: BigNumberish;
  };

  export type ValidatorInfoStructOutput = [
    lastAssignmentTime: bigint,
    lastRequestedValue: bigint,
    lastRequestedBond: bigint,
    depositValue: bigint,
    staked: boolean,
    exited: boolean,
    inQueue: boolean,
    inPrestake: boolean,
    expressUsed: boolean,
    dissolved: boolean,
    exiting: boolean,
    locked: boolean,
    exitBalance: bigint,
    lockedTime: bigint
  ] & {
    lastAssignmentTime: bigint;
    lastRequestedValue: bigint;
    lastRequestedBond: bigint;
    depositValue: bigint;
    staked: boolean;
    exited: boolean;
    inQueue: boolean;
    inPrestake: boolean;
    expressUsed: boolean;
    dissolved: boolean;
    exiting: boolean;
    locked: boolean;
    exitBalance: bigint;
    lockedTime: bigint;
  };
}

export interface RocketMegapoolDelegateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applyPenalty"
      | "assignFunds"
      | "calculatePendingRewards"
      | "calculateRewards"
      | "challengeExit"
      | "claim"
      | "deprecate"
      | "dequeue"
      | "dissolveValidator"
      | "distribute"
      | "getActiveValidatorCount"
      | "getAssignedValue"
      | "getDebt"
      | "getExitingValidatorCount"
      | "getExpirationTime"
      | "getLastDistributionTime"
      | "getLockedValidatorCount"
      | "getNewValidatorBondRequirement"
      | "getNodeAddress"
      | "getNodeBond"
      | "getNodeQueuedBond"
      | "getPendingRewards"
      | "getRefundValue"
      | "getUserCapital"
      | "getUserQueuedCapital"
      | "getValidatorCount"
      | "getValidatorInfo"
      | "getValidatorInfoAndPubkey"
      | "getValidatorPubkey"
      | "getWithdrawalCredentials"
      | "newValidator"
      | "notifyExit"
      | "notifyFinalBalance"
      | "notifyNotExit"
      | "reduceBond"
      | "repayDebt"
      | "stake"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MegapoolBondReduced"
      | "MegapoolDebtIncreased"
      | "MegapoolDebtReduced"
      | "MegapoolPenaltyApplied"
      | "MegapoolValidatorAssigned"
      | "MegapoolValidatorDequeued"
      | "MegapoolValidatorDissolved"
      | "MegapoolValidatorEnqueued"
      | "MegapoolValidatorExited"
      | "MegapoolValidatorExiting"
      | "MegapoolValidatorLocked"
      | "MegapoolValidatorStaked"
      | "MegapoolValidatorUnlocked"
      | "RewardsClaimed"
      | "RewardsDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "applyPenalty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePendingRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeExit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(functionFragment: "deprecate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "dequeue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dissolveValidator",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distribute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveValidatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAssignedValue",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getDebt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getExitingValidatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExpirationTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastDistributionTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLockedValidatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNewValidatorBondRequirement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeBond",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeQueuedBond",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRefundValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCapital",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserQueuedCapital",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorInfoAndPubkey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorPubkey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawalCredentials",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "newValidator",
    values: [BigNumberish, boolean, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "notifyExit",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "notifyFinalBalance",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "notifyNotExit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reduceBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "repayDebt", values?: undefined): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "applyPenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeExit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deprecate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dequeue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dissolveValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "distribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveValidatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssignedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDebt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getExitingValidatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpirationTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastDistributionTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLockedValidatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNewValidatorBondRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeQueuedBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRefundValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserQueuedCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorInfoAndPubkey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorPubkey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawalCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "notifyExit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "notifyFinalBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifyNotExit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reduceBond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repayDebt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace MegapoolBondReducedEvent {
  export type InputTuple = [amount: BigNumberish, time: BigNumberish];
  export type OutputTuple = [amount: bigint, time: bigint];
  export interface OutputObject {
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MegapoolDebtIncreasedEvent {
  export type InputTuple = [amount: BigNumberish, time: BigNumberish];
  export type OutputTuple = [amount: bigint, time: bigint];
  export interface OutputObject {
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MegapoolDebtReducedEvent {
  export type InputTuple = [amount: BigNumberish, time: BigNumberish];
  export type OutputTuple = [amount: bigint, time: bigint];
  export interface OutputObject {
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MegapoolPenaltyAppliedEvent {
  export type InputTuple = [amount: BigNumberish, time: BigNumberish];
  export type OutputTuple = [amount: bigint, time: bigint];
  export interface OutputObject {
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MegapoolValidatorAssignedEvent {
  export type InputTuple = [validatorId: BigNumberish, time: BigNumberish];
  export type OutputTuple = [validatorId: bigint, time: bigint];
  export interface OutputObject {
    validatorId: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MegapoolValidatorDequeuedEvent {
  export type InputTuple = [validatorId: BigNumberish, time: BigNumberish];
  export type OutputTuple = [validatorId: bigint, time: bigint];
  export interface OutputObject {
    validatorId: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MegapoolValidatorDissolvedEvent {
  export type InputTuple = [validatorId: BigNumberish, time: BigNumberish];
  export type OutputTuple = [validatorId: bigint, time: bigint];
  export interface OutputObject {
    validatorId: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MegapoolValidatorEnqueuedEvent {
  export type InputTuple = [validatorId: BigNumberish, time: BigNumberish];
  export type OutputTuple = [validatorId: bigint, time: bigint];
  export interface OutputObject {
    validatorId: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MegapoolValidatorExitedEvent {
  export type InputTuple = [validatorId: BigNumberish, time: BigNumberish];
  export type OutputTuple = [validatorId: bigint, time: bigint];
  export interface OutputObject {
    validatorId: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MegapoolValidatorExitingEvent {
  export type InputTuple = [validatorId: BigNumberish, time: BigNumberish];
  export type OutputTuple = [validatorId: bigint, time: bigint];
  export interface OutputObject {
    validatorId: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MegapoolValidatorLockedEvent {
  export type InputTuple = [validatorId: BigNumberish, time: BigNumberish];
  export type OutputTuple = [validatorId: bigint, time: bigint];
  export interface OutputObject {
    validatorId: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MegapoolValidatorStakedEvent {
  export type InputTuple = [validatorId: BigNumberish, time: BigNumberish];
  export type OutputTuple = [validatorId: bigint, time: bigint];
  export interface OutputObject {
    validatorId: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MegapoolValidatorUnlockedEvent {
  export type InputTuple = [validatorId: BigNumberish, time: BigNumberish];
  export type OutputTuple = [validatorId: bigint, time: bigint];
  export interface OutputObject {
    validatorId: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [amount: BigNumberish, time: BigNumberish];
  export type OutputTuple = [amount: bigint, time: bigint];
  export interface OutputObject {
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDistributedEvent {
  export type InputTuple = [
    nodeAmount: BigNumberish,
    voterAmount: BigNumberish,
    rethAmount: BigNumberish,
    protocolDaoAmount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [
    nodeAmount: bigint,
    voterAmount: bigint,
    rethAmount: bigint,
    protocolDaoAmount: bigint,
    time: bigint
  ];
  export interface OutputObject {
    nodeAmount: bigint;
    voterAmount: bigint;
    rethAmount: bigint;
    protocolDaoAmount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RocketMegapoolDelegate extends BaseContract {
  connect(runner?: ContractRunner | null): RocketMegapoolDelegate;
  waitForDeployment(): Promise<this>;

  interface: RocketMegapoolDelegateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applyPenalty: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  assignFunds: TypedContractMethod<
    [_validatorId: BigNumberish],
    [void],
    "payable"
  >;

  calculatePendingRewards: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        nodeRewards: bigint;
        voterRewards: bigint;
        protocolDAORewards: bigint;
        rethRewards: bigint;
      }
    ],
    "view"
  >;

  calculateRewards: TypedContractMethod<
    [_amount: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        nodeRewards: bigint;
        voterRewards: bigint;
        protocolDAORewards: bigint;
        rethRewards: bigint;
      }
    ],
    "view"
  >;

  challengeExit: TypedContractMethod<
    [_validatorId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<[], [void], "nonpayable">;

  deprecate: TypedContractMethod<[], [void], "nonpayable">;

  dequeue: TypedContractMethod<
    [_validatorId: BigNumberish],
    [void],
    "nonpayable"
  >;

  dissolveValidator: TypedContractMethod<
    [_validatorId: BigNumberish],
    [void],
    "nonpayable"
  >;

  distribute: TypedContractMethod<[], [void], "nonpayable">;

  getActiveValidatorCount: TypedContractMethod<[], [bigint], "view">;

  getAssignedValue: TypedContractMethod<[], [bigint], "view">;

  getDebt: TypedContractMethod<[], [bigint], "view">;

  getExitingValidatorCount: TypedContractMethod<[], [bigint], "view">;

  getExpirationTime: TypedContractMethod<[], [bigint], "view">;

  getLastDistributionTime: TypedContractMethod<[], [bigint], "view">;

  getLockedValidatorCount: TypedContractMethod<[], [bigint], "view">;

  getNewValidatorBondRequirement: TypedContractMethod<[], [bigint], "view">;

  getNodeAddress: TypedContractMethod<[], [string], "view">;

  getNodeBond: TypedContractMethod<[], [bigint], "view">;

  getNodeQueuedBond: TypedContractMethod<[], [bigint], "view">;

  getPendingRewards: TypedContractMethod<[], [bigint], "view">;

  getRefundValue: TypedContractMethod<[], [bigint], "view">;

  getUserCapital: TypedContractMethod<[], [bigint], "view">;

  getUserQueuedCapital: TypedContractMethod<[], [bigint], "view">;

  getValidatorCount: TypedContractMethod<[], [bigint], "view">;

  getValidatorInfo: TypedContractMethod<
    [_validatorId: BigNumberish],
    [RocketMegapoolStorageLayout.ValidatorInfoStructOutput],
    "view"
  >;

  getValidatorInfoAndPubkey: TypedContractMethod<
    [_validatorId: BigNumberish],
    [
      [RocketMegapoolStorageLayout.ValidatorInfoStructOutput, string] & {
        info: RocketMegapoolStorageLayout.ValidatorInfoStructOutput;
        pubkey: string;
      }
    ],
    "view"
  >;

  getValidatorPubkey: TypedContractMethod<
    [_validatorId: BigNumberish],
    [string],
    "view"
  >;

  getWithdrawalCredentials: TypedContractMethod<[], [string], "view">;

  newValidator: TypedContractMethod<
    [
      _bondAmount: BigNumberish,
      _useExpressTicket: boolean,
      _validatorPubkey: BytesLike,
      _validatorSignature: BytesLike,
      _depositDataRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  notifyExit: TypedContractMethod<
    [
      _validatorId: BigNumberish,
      _withdrawableEpoch: BigNumberish,
      _recentEpoch: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  notifyFinalBalance: TypedContractMethod<
    [
      _validatorId: BigNumberish,
      _amountInGwei: BigNumberish,
      _caller: AddressLike,
      _withdrawalEpoch: BigNumberish,
      _recentEpoch: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  notifyNotExit: TypedContractMethod<
    [_validatorId: BigNumberish, _slotTimestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  reduceBond: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  repayDebt: TypedContractMethod<[], [void], "payable">;

  stake: TypedContractMethod<
    [_validatorId: BigNumberish],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applyPenalty"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignFunds"
  ): TypedContractMethod<[_validatorId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "calculatePendingRewards"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        nodeRewards: bigint;
        voterRewards: bigint;
        protocolDAORewards: bigint;
        rethRewards: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateRewards"
  ): TypedContractMethod<
    [_amount: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        nodeRewards: bigint;
        voterRewards: bigint;
        protocolDAORewards: bigint;
        rethRewards: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "challengeExit"
  ): TypedContractMethod<[_validatorId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deprecate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dequeue"
  ): TypedContractMethod<[_validatorId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dissolveValidator"
  ): TypedContractMethod<[_validatorId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distribute"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveValidatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAssignedValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDebt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExitingValidatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExpirationTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLastDistributionTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLockedValidatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNewValidatorBondRequirement"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getNodeBond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeQueuedBond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingRewards"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRefundValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserCapital"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserQueuedCapital"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidatorInfo"
  ): TypedContractMethod<
    [_validatorId: BigNumberish],
    [RocketMegapoolStorageLayout.ValidatorInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidatorInfoAndPubkey"
  ): TypedContractMethod<
    [_validatorId: BigNumberish],
    [
      [RocketMegapoolStorageLayout.ValidatorInfoStructOutput, string] & {
        info: RocketMegapoolStorageLayout.ValidatorInfoStructOutput;
        pubkey: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidatorPubkey"
  ): TypedContractMethod<[_validatorId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getWithdrawalCredentials"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "newValidator"
  ): TypedContractMethod<
    [
      _bondAmount: BigNumberish,
      _useExpressTicket: boolean,
      _validatorPubkey: BytesLike,
      _validatorSignature: BytesLike,
      _depositDataRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "notifyExit"
  ): TypedContractMethod<
    [
      _validatorId: BigNumberish,
      _withdrawableEpoch: BigNumberish,
      _recentEpoch: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "notifyFinalBalance"
  ): TypedContractMethod<
    [
      _validatorId: BigNumberish,
      _amountInGwei: BigNumberish,
      _caller: AddressLike,
      _withdrawalEpoch: BigNumberish,
      _recentEpoch: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "notifyNotExit"
  ): TypedContractMethod<
    [_validatorId: BigNumberish, _slotTimestamp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reduceBond"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repayDebt"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[_validatorId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "MegapoolBondReduced"
  ): TypedContractEvent<
    MegapoolBondReducedEvent.InputTuple,
    MegapoolBondReducedEvent.OutputTuple,
    MegapoolBondReducedEvent.OutputObject
  >;
  getEvent(
    key: "MegapoolDebtIncreased"
  ): TypedContractEvent<
    MegapoolDebtIncreasedEvent.InputTuple,
    MegapoolDebtIncreasedEvent.OutputTuple,
    MegapoolDebtIncreasedEvent.OutputObject
  >;
  getEvent(
    key: "MegapoolDebtReduced"
  ): TypedContractEvent<
    MegapoolDebtReducedEvent.InputTuple,
    MegapoolDebtReducedEvent.OutputTuple,
    MegapoolDebtReducedEvent.OutputObject
  >;
  getEvent(
    key: "MegapoolPenaltyApplied"
  ): TypedContractEvent<
    MegapoolPenaltyAppliedEvent.InputTuple,
    MegapoolPenaltyAppliedEvent.OutputTuple,
    MegapoolPenaltyAppliedEvent.OutputObject
  >;
  getEvent(
    key: "MegapoolValidatorAssigned"
  ): TypedContractEvent<
    MegapoolValidatorAssignedEvent.InputTuple,
    MegapoolValidatorAssignedEvent.OutputTuple,
    MegapoolValidatorAssignedEvent.OutputObject
  >;
  getEvent(
    key: "MegapoolValidatorDequeued"
  ): TypedContractEvent<
    MegapoolValidatorDequeuedEvent.InputTuple,
    MegapoolValidatorDequeuedEvent.OutputTuple,
    MegapoolValidatorDequeuedEvent.OutputObject
  >;
  getEvent(
    key: "MegapoolValidatorDissolved"
  ): TypedContractEvent<
    MegapoolValidatorDissolvedEvent.InputTuple,
    MegapoolValidatorDissolvedEvent.OutputTuple,
    MegapoolValidatorDissolvedEvent.OutputObject
  >;
  getEvent(
    key: "MegapoolValidatorEnqueued"
  ): TypedContractEvent<
    MegapoolValidatorEnqueuedEvent.InputTuple,
    MegapoolValidatorEnqueuedEvent.OutputTuple,
    MegapoolValidatorEnqueuedEvent.OutputObject
  >;
  getEvent(
    key: "MegapoolValidatorExited"
  ): TypedContractEvent<
    MegapoolValidatorExitedEvent.InputTuple,
    MegapoolValidatorExitedEvent.OutputTuple,
    MegapoolValidatorExitedEvent.OutputObject
  >;
  getEvent(
    key: "MegapoolValidatorExiting"
  ): TypedContractEvent<
    MegapoolValidatorExitingEvent.InputTuple,
    MegapoolValidatorExitingEvent.OutputTuple,
    MegapoolValidatorExitingEvent.OutputObject
  >;
  getEvent(
    key: "MegapoolValidatorLocked"
  ): TypedContractEvent<
    MegapoolValidatorLockedEvent.InputTuple,
    MegapoolValidatorLockedEvent.OutputTuple,
    MegapoolValidatorLockedEvent.OutputObject
  >;
  getEvent(
    key: "MegapoolValidatorStaked"
  ): TypedContractEvent<
    MegapoolValidatorStakedEvent.InputTuple,
    MegapoolValidatorStakedEvent.OutputTuple,
    MegapoolValidatorStakedEvent.OutputObject
  >;
  getEvent(
    key: "MegapoolValidatorUnlocked"
  ): TypedContractEvent<
    MegapoolValidatorUnlockedEvent.InputTuple,
    MegapoolValidatorUnlockedEvent.OutputTuple,
    MegapoolValidatorUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDistributed"
  ): TypedContractEvent<
    RewardsDistributedEvent.InputTuple,
    RewardsDistributedEvent.OutputTuple,
    RewardsDistributedEvent.OutputObject
  >;

  filters: {
    "MegapoolBondReduced(uint256,uint256)": TypedContractEvent<
      MegapoolBondReducedEvent.InputTuple,
      MegapoolBondReducedEvent.OutputTuple,
      MegapoolBondReducedEvent.OutputObject
    >;
    MegapoolBondReduced: TypedContractEvent<
      MegapoolBondReducedEvent.InputTuple,
      MegapoolBondReducedEvent.OutputTuple,
      MegapoolBondReducedEvent.OutputObject
    >;

    "MegapoolDebtIncreased(uint256,uint256)": TypedContractEvent<
      MegapoolDebtIncreasedEvent.InputTuple,
      MegapoolDebtIncreasedEvent.OutputTuple,
      MegapoolDebtIncreasedEvent.OutputObject
    >;
    MegapoolDebtIncreased: TypedContractEvent<
      MegapoolDebtIncreasedEvent.InputTuple,
      MegapoolDebtIncreasedEvent.OutputTuple,
      MegapoolDebtIncreasedEvent.OutputObject
    >;

    "MegapoolDebtReduced(uint256,uint256)": TypedContractEvent<
      MegapoolDebtReducedEvent.InputTuple,
      MegapoolDebtReducedEvent.OutputTuple,
      MegapoolDebtReducedEvent.OutputObject
    >;
    MegapoolDebtReduced: TypedContractEvent<
      MegapoolDebtReducedEvent.InputTuple,
      MegapoolDebtReducedEvent.OutputTuple,
      MegapoolDebtReducedEvent.OutputObject
    >;

    "MegapoolPenaltyApplied(uint256,uint256)": TypedContractEvent<
      MegapoolPenaltyAppliedEvent.InputTuple,
      MegapoolPenaltyAppliedEvent.OutputTuple,
      MegapoolPenaltyAppliedEvent.OutputObject
    >;
    MegapoolPenaltyApplied: TypedContractEvent<
      MegapoolPenaltyAppliedEvent.InputTuple,
      MegapoolPenaltyAppliedEvent.OutputTuple,
      MegapoolPenaltyAppliedEvent.OutputObject
    >;

    "MegapoolValidatorAssigned(uint256,uint256)": TypedContractEvent<
      MegapoolValidatorAssignedEvent.InputTuple,
      MegapoolValidatorAssignedEvent.OutputTuple,
      MegapoolValidatorAssignedEvent.OutputObject
    >;
    MegapoolValidatorAssigned: TypedContractEvent<
      MegapoolValidatorAssignedEvent.InputTuple,
      MegapoolValidatorAssignedEvent.OutputTuple,
      MegapoolValidatorAssignedEvent.OutputObject
    >;

    "MegapoolValidatorDequeued(uint256,uint256)": TypedContractEvent<
      MegapoolValidatorDequeuedEvent.InputTuple,
      MegapoolValidatorDequeuedEvent.OutputTuple,
      MegapoolValidatorDequeuedEvent.OutputObject
    >;
    MegapoolValidatorDequeued: TypedContractEvent<
      MegapoolValidatorDequeuedEvent.InputTuple,
      MegapoolValidatorDequeuedEvent.OutputTuple,
      MegapoolValidatorDequeuedEvent.OutputObject
    >;

    "MegapoolValidatorDissolved(uint256,uint256)": TypedContractEvent<
      MegapoolValidatorDissolvedEvent.InputTuple,
      MegapoolValidatorDissolvedEvent.OutputTuple,
      MegapoolValidatorDissolvedEvent.OutputObject
    >;
    MegapoolValidatorDissolved: TypedContractEvent<
      MegapoolValidatorDissolvedEvent.InputTuple,
      MegapoolValidatorDissolvedEvent.OutputTuple,
      MegapoolValidatorDissolvedEvent.OutputObject
    >;

    "MegapoolValidatorEnqueued(uint256,uint256)": TypedContractEvent<
      MegapoolValidatorEnqueuedEvent.InputTuple,
      MegapoolValidatorEnqueuedEvent.OutputTuple,
      MegapoolValidatorEnqueuedEvent.OutputObject
    >;
    MegapoolValidatorEnqueued: TypedContractEvent<
      MegapoolValidatorEnqueuedEvent.InputTuple,
      MegapoolValidatorEnqueuedEvent.OutputTuple,
      MegapoolValidatorEnqueuedEvent.OutputObject
    >;

    "MegapoolValidatorExited(uint32,uint256)": TypedContractEvent<
      MegapoolValidatorExitedEvent.InputTuple,
      MegapoolValidatorExitedEvent.OutputTuple,
      MegapoolValidatorExitedEvent.OutputObject
    >;
    MegapoolValidatorExited: TypedContractEvent<
      MegapoolValidatorExitedEvent.InputTuple,
      MegapoolValidatorExitedEvent.OutputTuple,
      MegapoolValidatorExitedEvent.OutputObject
    >;

    "MegapoolValidatorExiting(uint256,uint256)": TypedContractEvent<
      MegapoolValidatorExitingEvent.InputTuple,
      MegapoolValidatorExitingEvent.OutputTuple,
      MegapoolValidatorExitingEvent.OutputObject
    >;
    MegapoolValidatorExiting: TypedContractEvent<
      MegapoolValidatorExitingEvent.InputTuple,
      MegapoolValidatorExitingEvent.OutputTuple,
      MegapoolValidatorExitingEvent.OutputObject
    >;

    "MegapoolValidatorLocked(uint256,uint256)": TypedContractEvent<
      MegapoolValidatorLockedEvent.InputTuple,
      MegapoolValidatorLockedEvent.OutputTuple,
      MegapoolValidatorLockedEvent.OutputObject
    >;
    MegapoolValidatorLocked: TypedContractEvent<
      MegapoolValidatorLockedEvent.InputTuple,
      MegapoolValidatorLockedEvent.OutputTuple,
      MegapoolValidatorLockedEvent.OutputObject
    >;

    "MegapoolValidatorStaked(uint256,uint256)": TypedContractEvent<
      MegapoolValidatorStakedEvent.InputTuple,
      MegapoolValidatorStakedEvent.OutputTuple,
      MegapoolValidatorStakedEvent.OutputObject
    >;
    MegapoolValidatorStaked: TypedContractEvent<
      MegapoolValidatorStakedEvent.InputTuple,
      MegapoolValidatorStakedEvent.OutputTuple,
      MegapoolValidatorStakedEvent.OutputObject
    >;

    "MegapoolValidatorUnlocked(uint256,uint256)": TypedContractEvent<
      MegapoolValidatorUnlockedEvent.InputTuple,
      MegapoolValidatorUnlockedEvent.OutputTuple,
      MegapoolValidatorUnlockedEvent.OutputObject
    >;
    MegapoolValidatorUnlocked: TypedContractEvent<
      MegapoolValidatorUnlockedEvent.InputTuple,
      MegapoolValidatorUnlockedEvent.OutputTuple,
      MegapoolValidatorUnlockedEvent.OutputObject
    >;

    "RewardsClaimed(uint256,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "RewardsDistributed(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;
    RewardsDistributed: TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;
  };
}
