import {
    RocketDAOProtocol__factory as V131DAOProtocolFactory,
    RocketDAOProtocolSettingsMinipool__factory as V131MinipoolSettingsFactory,
    RocketDAOProtocolSettingsNetwork__factory as V131NetworkSettingsFactory,
    RocketDAOProtocolSettingsNode__factory as V131NodeSettingsFactory,
    RocketDAOProtocolSettingsRewards__factory as V131RewardsSettingsFactory,
    RocketDAOProtocolSettingsDeposit__factory as V131DepositSettingsFactory,
    RocketDAONodeTrusted__factory as V131DAONodeTrustedFactory,
    RocketDAONodeTrustedActions__factory as V131DAONodeTrustedActionsFactory,
    RocketDAONodeTrustedProposals__factory as V131DAONodeTrustedProposalsFactory,
    RocketDAONodeTrustedUpgrade__factory as V131DAONodeTrustedUpgradeFactory,
    RocketDAONodeTrustedSettingsProposals__factory as V131TrustedProposalSettingsFactory,
    RocketDAOProposal__factory as V131DAOProposalFactory,
    RocketDAOSecurity__factory as V131DAOSecurityFactory,
    RocketDAOSecurityActions__factory as V131DAOSecurityActionsFactory,
    RocketDAOSecurityProposals__factory as V131DAOSecurityProposalsFactory,
    RocketDAOProtocolSettingsSecurity__factory as V131SecuritySettingsFactory,
    RocketDAONodeTrustedSettingsMembers__factory as V131TrustedMemberSettingsFactory,
    RocketDAONodeTrustedSettingsMinipool__factory as V131TrustedMinipoolSettingsFactory,
    RocketDepositPool__factory as V131DepositPoolFactory,
    RocketMinipoolFactory__factory as V131MinipoolFactoryFactory,
    RocketMinipoolManager__factory as V131MinipoolManagerFactory,
    RocketMinipoolBondReducer__factory as V131MinipoolBondReducerFactory,
    RocketMinipoolPenalty__factory as V131MinipoolPenaltyFactory,
    RocketNetworkPrices__factory as V131NetworkPricesFactory,
    RocketNetworkBalances__factory as V131NetworkBalancesFactory,
    RocketNodeDeposit__factory as V131NodeDepositFactory,
    RocketNodeManager__factory as V131NodeManagerFactory,
    RocketNodeStaking__factory as V131NodeStakingFactory,
    RocketStorage__factory as V131StorageFactory,
    RocketTokenDummyRPL__factory as V131DummyRplFactory,
    RocketTokenRETH__factory as V131RethFactory,
    RocketTokenRPL__factory as V131RplFactory,
    RocketVault__factory as V131VaultFactory,
    RocketAuctionManager__factory as V131AuctionManagerFactory,
    RocketDAOProtocolSettingsAuction__factory as V131AuctionSettingsFactory,
    RocketRewardsPool__factory as V131RewardsPoolFactory,
    RocketSmoothingPool__factory as V131SmoothingPoolFactory,
    RocketClaimDAO__factory as V131ClaimDAOFactory,
    RocketMerkleDistributorMainnet__factory as V131MerkleDistributorFactory,
} from "../bindings/v1_3_1";
import {
    RocketDAOProtocol__factory as V14DAOProtocolFactory,
    RocketDAOProtocolSettingsMinipool__factory as V14MinipoolSettingsFactory,
    RocketDAOProtocolSettingsNetwork__factory as V14NetworkSettingsFactory,
    RocketDAOProtocolSettingsNode__factory as V14NodeSettingsFactory,
    RocketDAOProtocolSettingsRewards__factory as V14RewardsSettingsFactory,
    RocketDAONodeTrusted__factory as V14DAONodeTrustedFactory,
    RocketDAONodeTrustedActions__factory as V14DAONodeTrustedActionsFactory,
    RocketDAONodeTrustedProposals__factory as V14DAONodeTrustedProposalsFactory,
    RocketDAONodeTrustedUpgrade__factory as V14DAONodeTrustedUpgradeFactory,
    RocketDAONodeTrustedSettingsProposals__factory as V14TrustedProposalSettingsFactory,
    RocketDAOProposal__factory as V14DAOProposalFactory,
    RocketDAOSecurity__factory as V14DAOSecurityFactory,
    RocketDAOSecurityActions__factory as V14DAOSecurityActionsFactory,
    RocketDAOSecurityProposals__factory as V14DAOSecurityProposalsFactory,
    RocketDAOSecurityUpgrade__factory as V14DAOSecurityUpgradeFactory,
    RocketDAONodeTrustedSettingsMembers__factory as V14TrustedMemberSettingsFactory,
    RocketDAONodeTrustedSettingsMinipool__factory as V14TrustedMinipoolSettingsFactory,
    RocketDepositPool__factory as V14DepositPoolFactory,
    RocketMinipoolFactory__factory as V14MinipoolFactoryFactory,
    RocketMinipoolManager__factory as V14MinipoolManagerFactory,
    RocketNetworkPrices__factory as V14NetworkPricesFactory,
    RocketNetworkBalances__factory as V14NetworkBalancesFactory,
    RocketNodeDistributorFactory__factory as V14NodeDistributorFactoryFactory,
    RocketNodeDeposit__factory as V14NodeDepositFactory,
    RocketNodeManager__factory as V14NodeManagerFactory,
    RocketNodeStaking__factory as V14NodeStakingFactory,
    RocketStorage__factory as V14StorageFactory,
    RocketTokenDummyRPL__factory as V14DummyRplFactory,
    RocketTokenRETH__factory as V14RethFactory,
    RocketTokenRPL__factory as V14RplFactory,
    RocketVault__factory as V14VaultFactory,
    RocketAuctionManager__factory as V14AuctionManagerFactory,
    RocketDAOProtocolSettingsAuction__factory as V14AuctionSettingsFactory,
    RocketRewardsPool__factory as V14RewardsPoolFactory,
    RocketSmoothingPool__factory as V14SmoothingPoolFactory,
    RocketClaimDAO__factory as V14ClaimDAOFactory,
    RocketMerkleDistributorMainnet__factory as V14MerkleDistributorFactory,
    RocketMinipoolPenalty__factory as V14MinipoolPenaltyFactory,
    RocketNetworkPenalties__factory as V14NetworkPenaltiesFactory,
    RocketNetworkVoting__factory as V14NetworkVotingFactory,
    RocketNetworkRevenues__factory as V14NetworkRevenuesFactory,
    RocketMegapoolFactory__factory as V14MegapoolFactoryFactory,
    RocketMegapoolManager__factory as V14MegapoolManagerFactory,
    LinkedListStorage__factory as V14LinkedListStorageFactory,
    RocketDAOProtocolSettingsDeposit__factory as V14DepositSettingsFactory,
    RocketDAOProtocolSettingsMegapool__factory as V14MegapoolSettingsFactory,
    RocketDAOProtocolSettingsSecurity__factory as V14SecuritySettingsFactory,
    RocketDAOProtocolSettingsProposals__factory as V14ProposalSettingsFactory,
    RocketDAOProtocolSettingsInflation__factory as V14ProtocolInflationSettingsFactory,
    RocketDAOProtocolProposal__factory as V14ProtocolProposalFactory,
    RocketDAOProtocolProposals__factory as V14ProtocolProposalsFactory,
    RocketDAOProtocolVerifier__factory as V14ProtocolVerifierFactory,
} from "../bindings/v1_4";
import {
    BeaconStateVerifierMock__factory as CurrentBeaconStateVerifierFactory,
    RocketDAOProtocol__factory as CurrentDAOProtocolFactory,
    RocketDAOProtocolSettingsMegapool__factory as CurrentMegapoolSettingsFactory,
    RocketDAOProtocolSettingsMinipool__factory as CurrentMinipoolSettingsFactory,
    RocketDAOProtocolSettingsNetwork__factory as CurrentNetworkSettingsFactory,
    RocketDAOProtocolSettingsNode__factory as CurrentNodeSettingsFactory,
    RocketDAOProtocolSettingsRewards__factory as CurrentRewardsSettingsFactory,
    RocketDAOProtocolSettingsDeposit__factory as CurrentDepositSettingsFactory,
    RocketDAONodeTrusted__factory as CurrentDAONodeTrustedFactory,
    RocketDAONodeTrustedActions__factory as CurrentDAONodeTrustedActionsFactory,
    RocketDAONodeTrustedProposals__factory as CurrentDAONodeTrustedProposalsFactory,
    RocketDAONodeTrustedUpgrade__factory as CurrentDAONodeTrustedUpgradeFactory,
    RocketDAONodeTrustedSettingsProposals__factory as CurrentTrustedProposalSettingsFactory,
    RocketDAOProposal__factory as CurrentDAOProposalFactory,
    RocketDAOSecurity__factory as CurrentDAOSecurityFactory,
    RocketDAOSecurityActions__factory as CurrentDAOSecurityActionsFactory,
    RocketDAOSecurityProposals__factory as CurrentDAOSecurityProposalsFactory,
    RocketDAOSecurityUpgrade__factory as CurrentDAOSecurityUpgradeFactory,
    RocketDAOProtocolSettingsSecurity__factory as CurrentSecuritySettingsFactory,
    RocketDAONodeTrustedSettingsMembers__factory as CurrentTrustedMemberSettingsFactory,
    RocketDAONodeTrustedSettingsMinipool__factory as CurrentTrustedMinipoolSettingsFactory,
    RocketDepositPool__factory as CurrentDepositPoolFactory,
    RocketMinipoolFactory__factory as CurrentMinipoolFactoryFactory,
    RocketMinipoolManager__factory as CurrentMinipoolManagerFactory,
    RocketMinipoolPenalty__factory as CurrentMinipoolPenaltyFactory,
    RocketNetworkPrices__factory as CurrentNetworkPricesFactory,
    RocketNetworkBalances__factory as CurrentNetworkBalancesFactory,
    RocketNetworkVoting__factory as CurrentNetworkVotingFactory,
    RocketNetworkRevenues__factory as CurrentNetworkRevenuesFactory,
    RocketNetworkExit__factory as CurrentNetworkExitFactory,
    RocketNetworkPenalties__factory as CurrentNetworkPenaltiesFactory,
    RocketRewardsPool__factory as CurrentRewardsPoolFactory,
    RocketSmoothingPool__factory as CurrentSmoothingPoolFactory,
    RocketClaimDAO__factory as CurrentClaimDAOFactory,
    RocketMerkleDistributorMainnet__factory as CurrentMerkleDistributorFactory,
    RocketMegapoolFactory__factory as CurrentMegapoolFactoryFactory,
    RocketMegapoolManager__factory as CurrentMegapoolManagerFactory,
    RocketMegapoolPenalties__factory as CurrentMegapoolPenaltiesFactory,
    RocketNodeDeposit__factory as CurrentNodeDepositFactory,
    RocketNodeDistributorFactory__factory as CurrentNodeDistributorFactoryFactory,
    RocketNodeManager__factory as CurrentNodeManagerFactory,
    RocketNodeStaking__factory as CurrentNodeStakingFactory,
    RocketStorage__factory as CurrentStorageFactory,
    RocketTokenDummyRPL__factory as CurrentDummyRplFactory,
    RocketTokenRETH__factory as CurrentRethFactory,
    RocketTokenRPL__factory as CurrentRplFactory,
    RocketVault__factory as CurrentVaultFactory,
    RocketAuctionManager__factory as CurrentAuctionManagerFactory,
    RocketDAOProtocolSettingsAuction__factory as CurrentAuctionSettingsFactory,
    RocketUpgradeOneDotFive__factory,
} from "../bindings/current";
import type { ProtocolContext } from "../context";
import { getActiveAddress } from "../deployment";
import { ethers } from "../../../test-old/_utils/hardhat-runtime";
import type { CurrentContracts, V14Contracts } from "./contracts";
import { ProtocolCurrent, ProtocolV131, ProtocolV14 } from "./releases";

export function connectV131(context: ProtocolContext): ProtocolV131 {
    const signer = ethers.provider;
    const state = context.deployment;
    return new ProtocolV131(context, {
        rocketStorage: V131StorageFactory.connect(state.rocketStorageAddress, signer),
        rocketDAOProtocol: V131DAOProtocolFactory.connect(getActiveAddress(state, "rocketDAOProtocol"), signer),
        rocketDAONodeTrusted: V131DAONodeTrustedFactory.connect(getActiveAddress(state, "rocketDAONodeTrusted"), signer),
        rocketDAONodeTrustedActions: V131DAONodeTrustedActionsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedActions"), signer),
        rocketDAONodeTrustedProposals: V131DAONodeTrustedProposalsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedProposals"), signer),
        rocketDAONodeTrustedUpgrade: V131DAONodeTrustedUpgradeFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedUpgrade"), signer),
        rocketDAONodeTrustedSettingsProposals: V131TrustedProposalSettingsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedSettingsProposals"), signer),
        rocketDAOProposal: V131DAOProposalFactory.connect(getActiveAddress(state, "rocketDAOProposal"), signer),
        rocketDAOSecurity: V131DAOSecurityFactory.connect(getActiveAddress(state, "rocketDAOSecurity"), signer),
        rocketDAOSecurityActions: V131DAOSecurityActionsFactory.connect(getActiveAddress(state, "rocketDAOSecurityActions"), signer),
        rocketDAOSecurityProposals: V131DAOSecurityProposalsFactory.connect(getActiveAddress(state, "rocketDAOSecurityProposals"), signer),
        rocketDAONodeTrustedSettingsMembers: V131TrustedMemberSettingsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedSettingsMembers"), signer),
        rocketNodeManager: V131NodeManagerFactory.connect(getActiveAddress(state, "rocketNodeManager"), signer),
        rocketNodeStaking: V131NodeStakingFactory.connect(getActiveAddress(state, "rocketNodeStaking"), signer),
        rocketTokenRPL: V131RplFactory.connect(getActiveAddress(state, "rocketTokenRPL"), signer),
        rocketTokenRPLFixedSupply: V131DummyRplFactory.connect(getActiveAddress(state, "rocketTokenRPLFixedSupply"), signer),
        rocketTokenRETH: V131RethFactory.connect(getActiveAddress(state, "rocketTokenRETH"), signer),
        rocketVault: V131VaultFactory.connect(getActiveAddress(state, "rocketVault"), signer),
        rocketAuctionManager: V131AuctionManagerFactory.connect(getActiveAddress(state, "rocketAuctionManager"), signer),
        rocketDepositPool: V131DepositPoolFactory.connect(getActiveAddress(state, "rocketDepositPool"), signer),
        rocketNodeDeposit: V131NodeDepositFactory.connect(getActiveAddress(state, "rocketNodeDeposit"), signer),
        rocketMinipoolManager: V131MinipoolManagerFactory.connect(getActiveAddress(state, "rocketMinipoolManager"), signer),
        rocketMinipoolFactory: V131MinipoolFactoryFactory.connect(getActiveAddress(state, "rocketMinipoolFactory"), signer),
        rocketMinipoolBondReducer: V131MinipoolBondReducerFactory.connect(getActiveAddress(state, "rocketMinipoolBondReducer"), signer),
        rocketMinipoolPenalty: V131MinipoolPenaltyFactory.connect(getActiveAddress(state, "rocketMinipoolPenalty"), signer),
        rocketDAOProtocolSettingsNode: V131NodeSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsNode"), signer),
        rocketDAOProtocolSettingsRewards: V131RewardsSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsRewards"), signer),
        rocketDAOProtocolSettingsMinipool: V131MinipoolSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsMinipool"), signer),
        rocketDAOProtocolSettingsNetwork: V131NetworkSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsNetwork"), signer),
        rocketDAOProtocolSettingsDeposit: V131DepositSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsDeposit"), signer),
        rocketDAOProtocolSettingsAuction: V131AuctionSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsAuction"), signer),
        rocketDAOProtocolSettingsSecurity: V131SecuritySettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsSecurity"), signer),
        rocketDAONodeTrustedSettingsMinipool: V131TrustedMinipoolSettingsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedSettingsMinipool"), signer),
        rocketNetworkPrices: V131NetworkPricesFactory.connect(getActiveAddress(state, "rocketNetworkPrices"), signer),
        rocketNetworkBalances: V131NetworkBalancesFactory.connect(getActiveAddress(state, "rocketNetworkBalances"), signer),
        rocketRewardsPool: V131RewardsPoolFactory.connect(getActiveAddress(state, "rocketRewardsPool"), signer),
        rocketSmoothingPool: V131SmoothingPoolFactory.connect(getActiveAddress(state, "rocketSmoothingPool"), signer),
        rocketClaimDAO: V131ClaimDAOFactory.connect(getActiveAddress(state, "rocketClaimDAO"), signer),
        rocketMerkleDistributorMainnet: V131MerkleDistributorFactory.connect(getActiveAddress(state, "rocketMerkleDistributorMainnet"), signer),
    });
}

export function connectV14(context: ProtocolContext): ProtocolV14 {
    return new ProtocolV14(context, connectV14Contracts(context));
}

function connectV14Contracts(context: ProtocolContext): V14Contracts {
    const signer = ethers.provider;
    const state = context.deployment;
    return {
        rocketStorage: V14StorageFactory.connect(state.rocketStorageAddress, signer),
        rocketDAOProtocol: V14DAOProtocolFactory.connect(getActiveAddress(state, "rocketDAOProtocol"), signer),
        rocketDAONodeTrusted: V14DAONodeTrustedFactory.connect(getActiveAddress(state, "rocketDAONodeTrusted"), signer),
        rocketDAONodeTrustedActions: V14DAONodeTrustedActionsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedActions"), signer),
        rocketDAONodeTrustedProposals: V14DAONodeTrustedProposalsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedProposals"), signer),
        rocketDAONodeTrustedUpgrade: V14DAONodeTrustedUpgradeFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedUpgrade"), signer),
        rocketDAONodeTrustedSettingsProposals: V14TrustedProposalSettingsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedSettingsProposals"), signer),
        rocketDAOProposal: V14DAOProposalFactory.connect(getActiveAddress(state, "rocketDAOProposal"), signer),
        rocketDAOSecurity: V14DAOSecurityFactory.connect(getActiveAddress(state, "rocketDAOSecurity"), signer),
        rocketDAOSecurityActions: V14DAOSecurityActionsFactory.connect(getActiveAddress(state, "rocketDAOSecurityActions"), signer),
        rocketDAOSecurityProposals: V14DAOSecurityProposalsFactory.connect(getActiveAddress(state, "rocketDAOSecurityProposals"), signer),
        rocketDAOSecurityUpgrade: V14DAOSecurityUpgradeFactory.connect(getActiveAddress(state, "rocketDAOSecurityUpgrade"), signer),
        rocketDAONodeTrustedSettingsMembers: V14TrustedMemberSettingsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedSettingsMembers"), signer),
        rocketNodeManager: V14NodeManagerFactory.connect(getActiveAddress(state, "rocketNodeManager"), signer),
        rocketNodeStaking: V14NodeStakingFactory.connect(getActiveAddress(state, "rocketNodeStaking"), signer),
        rocketTokenRPL: V14RplFactory.connect(getActiveAddress(state, "rocketTokenRPL"), signer),
        rocketTokenRPLFixedSupply: V14DummyRplFactory.connect(getActiveAddress(state, "rocketTokenRPLFixedSupply"), signer),
        rocketTokenRETH: V14RethFactory.connect(getActiveAddress(state, "rocketTokenRETH"), signer),
        rocketVault: V14VaultFactory.connect(getActiveAddress(state, "rocketVault"), signer),
        rocketAuctionManager: V14AuctionManagerFactory.connect(getActiveAddress(state, "rocketAuctionManager"), signer),
        rocketDepositPool: V14DepositPoolFactory.connect(getActiveAddress(state, "rocketDepositPool"), signer),
        rocketNodeDistributorFactory: V14NodeDistributorFactoryFactory.connect(getActiveAddress(state, "rocketNodeDistributorFactory"), signer),
        rocketNodeDeposit: V14NodeDepositFactory.connect(getActiveAddress(state, "rocketNodeDeposit"), signer),
        rocketMinipoolManager: V14MinipoolManagerFactory.connect(getActiveAddress(state, "rocketMinipoolManager"), signer),
        rocketMinipoolFactory: V14MinipoolFactoryFactory.connect(getActiveAddress(state, "rocketMinipoolFactory"), signer),
        rocketDAOProtocolSettingsNode: V14NodeSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsNode"), signer),
        rocketDAOProtocolSettingsRewards: V14RewardsSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsRewards"), signer),
        rocketDAOProtocolSettingsMinipool: V14MinipoolSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsMinipool"), signer),
        rocketDAOProtocolSettingsNetwork: V14NetworkSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsNetwork"), signer),
        rocketDAONodeTrustedSettingsMinipool: V14TrustedMinipoolSettingsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedSettingsMinipool"), signer),
        rocketNetworkPrices: V14NetworkPricesFactory.connect(getActiveAddress(state, "rocketNetworkPrices"), signer),
        rocketNetworkBalances: V14NetworkBalancesFactory.connect(getActiveAddress(state, "rocketNetworkBalances"), signer),
        rocketRewardsPool: V14RewardsPoolFactory.connect(getActiveAddress(state, "rocketRewardsPool"), signer),
        rocketSmoothingPool: V14SmoothingPoolFactory.connect(getActiveAddress(state, "rocketSmoothingPool"), signer),
        rocketClaimDAO: V14ClaimDAOFactory.connect(getActiveAddress(state, "rocketClaimDAO"), signer),
        rocketMerkleDistributorMainnet: V14MerkleDistributorFactory.connect(getActiveAddress(state, "rocketMerkleDistributorMainnet"), signer),
        rocketMinipoolPenalty: V14MinipoolPenaltyFactory.connect(getActiveAddress(state, "rocketMinipoolPenalty"), signer),
        rocketNetworkPenalties: V14NetworkPenaltiesFactory.connect(getActiveAddress(state, "rocketNetworkPenalties"), signer),
        rocketNetworkVoting: V14NetworkVotingFactory.connect(getActiveAddress(state, "rocketNetworkVoting"), signer),
        rocketNetworkRevenues: V14NetworkRevenuesFactory.connect(getActiveAddress(state, "rocketNetworkRevenues"), signer),
        rocketMegapoolFactory: V14MegapoolFactoryFactory.connect(getActiveAddress(state, "rocketMegapoolFactory"), signer),
        rocketMegapoolManager: V14MegapoolManagerFactory.connect(getActiveAddress(state, "rocketMegapoolManager"), signer),
        linkedListStorage: V14LinkedListStorageFactory.connect(getActiveAddress(state, "linkedListStorage"), signer),
        rocketDAOProtocolSettingsDeposit: V14DepositSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsDeposit"), signer),
        rocketDAOProtocolSettingsMegapool: V14MegapoolSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsMegapool"), signer),
        rocketDAOProtocolSettingsSecurity: V14SecuritySettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsSecurity"), signer),
        rocketDAOProtocolSettingsProposals: V14ProposalSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsProposals"), signer),
        rocketDAOProtocolSettingsAuction: V14AuctionSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsAuction"), signer),
        rocketDAOProtocolSettingsInflation: V14ProtocolInflationSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsInflation"), signer),
        rocketDAOProtocolProposal: V14ProtocolProposalFactory.connect(getActiveAddress(state, "rocketDAOProtocolProposal"), signer),
        rocketDAOProtocolProposals: V14ProtocolProposalsFactory.connect(getActiveAddress(state, "rocketDAOProtocolProposals"), signer),
        rocketDAOProtocolVerifier: V14ProtocolVerifierFactory.connect(getActiveAddress(state, "rocketDAOProtocolVerifier"), signer),
    };
}

export function connectCurrent(context: ProtocolContext): ProtocolCurrent {
    const signer = ethers.provider;
    const state = context.deployment;
    const contracts: CurrentContracts = {
        beaconStateVerifier: CurrentBeaconStateVerifierFactory.connect(getActiveAddress(state, "beaconStateVerifier"), signer),
        rocketStorage: CurrentStorageFactory.connect(state.rocketStorageAddress, signer),
        rocketDAOProtocol: CurrentDAOProtocolFactory.connect(getActiveAddress(state, "rocketDAOProtocol"), signer),
        rocketDAONodeTrusted: CurrentDAONodeTrustedFactory.connect(getActiveAddress(state, "rocketDAONodeTrusted"), signer),
        rocketDAONodeTrustedActions: CurrentDAONodeTrustedActionsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedActions"), signer),
        rocketDAONodeTrustedProposals: CurrentDAONodeTrustedProposalsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedProposals"), signer),
        rocketDAONodeTrustedUpgrade: CurrentDAONodeTrustedUpgradeFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedUpgrade"), signer),
        rocketDAONodeTrustedSettingsProposals: CurrentTrustedProposalSettingsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedSettingsProposals"), signer),
        rocketDAOProposal: CurrentDAOProposalFactory.connect(getActiveAddress(state, "rocketDAOProposal"), signer),
        rocketDAOSecurity: CurrentDAOSecurityFactory.connect(getActiveAddress(state, "rocketDAOSecurity"), signer),
        rocketDAOSecurityActions: CurrentDAOSecurityActionsFactory.connect(getActiveAddress(state, "rocketDAOSecurityActions"), signer),
        rocketDAOSecurityProposals: CurrentDAOSecurityProposalsFactory.connect(getActiveAddress(state, "rocketDAOSecurityProposals"), signer),
        rocketDAOSecurityUpgrade: CurrentDAOSecurityUpgradeFactory.connect(getActiveAddress(state, "rocketDAOSecurityUpgrade"), signer),
        rocketDAONodeTrustedSettingsMembers: CurrentTrustedMemberSettingsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedSettingsMembers"), signer),
        rocketNodeManager: CurrentNodeManagerFactory.connect(getActiveAddress(state, "rocketNodeManager"), signer),
        rocketNodeStaking: CurrentNodeStakingFactory.connect(getActiveAddress(state, "rocketNodeStaking"), signer),
        rocketTokenRPL: CurrentRplFactory.connect(getActiveAddress(state, "rocketTokenRPL"), signer),
        rocketTokenRPLFixedSupply: CurrentDummyRplFactory.connect(getActiveAddress(state, "rocketTokenRPLFixedSupply"), signer),
        rocketTokenRETH: CurrentRethFactory.connect(getActiveAddress(state, "rocketTokenRETH"), signer),
        rocketVault: CurrentVaultFactory.connect(getActiveAddress(state, "rocketVault"), signer),
        rocketAuctionManager: CurrentAuctionManagerFactory.connect(getActiveAddress(state, "rocketAuctionManager"), signer),
        rocketDepositPool: CurrentDepositPoolFactory.connect(getActiveAddress(state, "rocketDepositPool"), signer),
        rocketNodeDistributorFactory: CurrentNodeDistributorFactoryFactory.connect(getActiveAddress(state, "rocketNodeDistributorFactory"), signer),
        rocketNodeDeposit: CurrentNodeDepositFactory.connect(getActiveAddress(state, "rocketNodeDeposit"), signer),
        rocketMinipoolManager: CurrentMinipoolManagerFactory.connect(getActiveAddress(state, "rocketMinipoolManager"), signer),
        rocketMinipoolFactory: CurrentMinipoolFactoryFactory.connect(getActiveAddress(state, "rocketMinipoolFactory"), signer),
        rocketMinipoolPenalty: CurrentMinipoolPenaltyFactory.connect(getActiveAddress(state, "rocketMinipoolPenalty"), signer),
        rocketDAOProtocolSettingsNode: CurrentNodeSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsNode"), signer),
        rocketDAOProtocolSettingsRewards: CurrentRewardsSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsRewards"), signer),
        rocketDAOProtocolSettingsMinipool: CurrentMinipoolSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsMinipool"), signer),
        rocketDAOProtocolSettingsNetwork: CurrentNetworkSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsNetwork"), signer),
        rocketDAOProtocolSettingsMegapool: CurrentMegapoolSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsMegapool"), signer),
        rocketDAOProtocolSettingsDeposit: CurrentDepositSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsDeposit"), signer),
        rocketDAOProtocolSettingsAuction: CurrentAuctionSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsAuction"), signer),
        rocketDAOProtocolSettingsSecurity: CurrentSecuritySettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsSecurity"), signer),
        rocketDAONodeTrustedSettingsMinipool: CurrentTrustedMinipoolSettingsFactory.connect(getActiveAddress(state, "rocketDAONodeTrustedSettingsMinipool"), signer),
        rocketNetworkPrices: CurrentNetworkPricesFactory.connect(getActiveAddress(state, "rocketNetworkPrices"), signer),
        rocketNetworkBalances: CurrentNetworkBalancesFactory.connect(getActiveAddress(state, "rocketNetworkBalances"), signer),
        rocketNetworkVoting: CurrentNetworkVotingFactory.connect(getActiveAddress(state, "rocketNetworkVoting"), signer),
        rocketNetworkRevenues: CurrentNetworkRevenuesFactory.connect(getActiveAddress(state, "rocketNetworkRevenues"), signer),
        rocketNetworkExit: CurrentNetworkExitFactory.connect(getActiveAddress(state, "rocketNetworkExit"), signer),
        rocketNetworkPenalties: CurrentNetworkPenaltiesFactory.connect(getActiveAddress(state, "rocketNetworkPenalties"), signer),
        rocketRewardsPool: CurrentRewardsPoolFactory.connect(getActiveAddress(state, "rocketRewardsPool"), signer),
        rocketSmoothingPool: CurrentSmoothingPoolFactory.connect(getActiveAddress(state, "rocketSmoothingPool"), signer),
        rocketClaimDAO: CurrentClaimDAOFactory.connect(getActiveAddress(state, "rocketClaimDAO"), signer),
        rocketMerkleDistributorMainnet: CurrentMerkleDistributorFactory.connect(getActiveAddress(state, "rocketMerkleDistributorMainnet"), signer),
        rocketMegapoolFactory: CurrentMegapoolFactoryFactory.connect(getActiveAddress(state, "rocketMegapoolFactory"), signer),
        rocketMegapoolManager: CurrentMegapoolManagerFactory.connect(getActiveAddress(state, "rocketMegapoolManager"), signer),
        rocketMegapoolPenalties: CurrentMegapoolPenaltiesFactory.connect(getActiveAddress(state, "rocketMegapoolPenalties"), signer),
        linkedListStorage: V14LinkedListStorageFactory.connect(getActiveAddress(state, "linkedListStorage"), signer),
        rocketUpgradeOneDotFive: RocketUpgradeOneDotFive__factory.connect(
            getActiveAddress(state, "rocketUpgradeOneDotFive"),
            signer,
        ),
        rocketDAOProtocolProposal: V14ProtocolProposalFactory.connect(getActiveAddress(state, "rocketDAOProtocolProposal"), signer),
        rocketDAOProtocolProposals: V14ProtocolProposalsFactory.connect(getActiveAddress(state, "rocketDAOProtocolProposals"), signer),
        rocketDAOProtocolVerifier: V14ProtocolVerifierFactory.connect(getActiveAddress(state, "rocketDAOProtocolVerifier"), signer),
        rocketDAOProtocolSettingsProposals: V14ProposalSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsProposals"), signer),
        rocketDAOProtocolSettingsInflation: V14ProtocolInflationSettingsFactory.connect(getActiveAddress(state, "rocketDAOProtocolSettingsInflation"), signer),
    };
    return new ProtocolCurrent(context, contracts);
}
