/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addUint"
      | "confirmGuardian"
      | "confirmWithdrawalAddress"
      | "deleteAddress"
      | "deleteBool"
      | "deleteBytes"
      | "deleteBytes32"
      | "deleteInt"
      | "deleteString"
      | "deleteUint"
      | "getAddress"
      | "getBool"
      | "getBytes"
      | "getBytes32"
      | "getDeployedStatus"
      | "getGuardian"
      | "getInt"
      | "getNodePendingWithdrawalAddress"
      | "getNodeWithdrawalAddress"
      | "getString"
      | "getUint"
      | "setAddress"
      | "setBool"
      | "setBytes"
      | "setBytes32"
      | "setDeployedStatus"
      | "setGuardian"
      | "setInt"
      | "setString"
      | "setUint"
      | "setWithdrawalAddress"
      | "subUint"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GuardianChanged" | "NodeWithdrawalAddressSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addUint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confirmWithdrawalAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBool",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBytes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBytes32",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteInt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteUint",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getBool", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getBytes", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getBytes32",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployedStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getInt", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getNodePendingWithdrawalAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeWithdrawalAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getUint", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBool",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes32",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDeployedStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGuardian",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setInt",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setString",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setUint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWithdrawalAddress",
    values: [AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "subUint",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmWithdrawalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteBool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteBytes32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteInt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteUint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBytes32", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getInt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNodePendingWithdrawalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeWithdrawalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getString", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBytes32", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDeployedStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setInt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setString", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setWithdrawalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subUint", data: BytesLike): Result;
}

export namespace GuardianChangedEvent {
  export type InputTuple = [oldGuardian: AddressLike, newGuardian: AddressLike];
  export type OutputTuple = [oldGuardian: string, newGuardian: string];
  export interface OutputObject {
    oldGuardian: string;
    newGuardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeWithdrawalAddressSetEvent {
  export type InputTuple = [
    node: AddressLike,
    withdrawalAddress: AddressLike,
    time: BigNumberish
  ];
  export type OutputTuple = [
    node: string,
    withdrawalAddress: string,
    time: bigint
  ];
  export interface OutputObject {
    node: string;
    withdrawalAddress: string;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RocketStorage extends BaseContract {
  connect(runner?: ContractRunner | null): RocketStorage;
  waitForDeployment(): Promise<this>;

  interface: RocketStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addUint: TypedContractMethod<
    [_key: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  confirmGuardian: TypedContractMethod<[], [void], "nonpayable">;

  confirmWithdrawalAddress: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  deleteAddress: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  deleteBool: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  deleteBytes: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  deleteBytes32: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  deleteInt: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  deleteString: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  deleteUint: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  getAddress: TypedContractMethod<[_key: BytesLike], [string], "view">;

  getBool: TypedContractMethod<[_key: BytesLike], [boolean], "view">;

  getBytes: TypedContractMethod<[_key: BytesLike], [string], "view">;

  getBytes32: TypedContractMethod<[_key: BytesLike], [string], "view">;

  getDeployedStatus: TypedContractMethod<[], [boolean], "view">;

  getGuardian: TypedContractMethod<[], [string], "view">;

  getInt: TypedContractMethod<[_key: BytesLike], [bigint], "view">;

  getNodePendingWithdrawalAddress: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [string],
    "view"
  >;

  getNodeWithdrawalAddress: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [string],
    "view"
  >;

  getString: TypedContractMethod<[_key: BytesLike], [string], "view">;

  getUint: TypedContractMethod<[_key: BytesLike], [bigint], "view">;

  setAddress: TypedContractMethod<
    [_key: BytesLike, _value: AddressLike],
    [void],
    "nonpayable"
  >;

  setBool: TypedContractMethod<
    [_key: BytesLike, _value: boolean],
    [void],
    "nonpayable"
  >;

  setBytes: TypedContractMethod<
    [_key: BytesLike, _value: BytesLike],
    [void],
    "nonpayable"
  >;

  setBytes32: TypedContractMethod<
    [_key: BytesLike, _value: BytesLike],
    [void],
    "nonpayable"
  >;

  setDeployedStatus: TypedContractMethod<[], [void], "nonpayable">;

  setGuardian: TypedContractMethod<
    [_newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setInt: TypedContractMethod<
    [_key: BytesLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;

  setString: TypedContractMethod<
    [_key: BytesLike, _value: string],
    [void],
    "nonpayable"
  >;

  setUint: TypedContractMethod<
    [_key: BytesLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;

  setWithdrawalAddress: TypedContractMethod<
    [
      _nodeAddress: AddressLike,
      _newWithdrawalAddress: AddressLike,
      _confirm: boolean
    ],
    [void],
    "nonpayable"
  >;

  subUint: TypedContractMethod<
    [_key: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addUint"
  ): TypedContractMethod<
    [_key: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confirmGuardian"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmWithdrawalAddress"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteAddress"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteBool"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteBytes"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteBytes32"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteInt"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteString"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteUint"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<[_key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getBool"
  ): TypedContractMethod<[_key: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBytes"
  ): TypedContractMethod<[_key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getBytes32"
  ): TypedContractMethod<[_key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDeployedStatus"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getGuardian"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getInt"
  ): TypedContractMethod<[_key: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodePendingWithdrawalAddress"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getNodeWithdrawalAddress"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getString"
  ): TypedContractMethod<[_key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUint"
  ): TypedContractMethod<[_key: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAddress"
  ): TypedContractMethod<
    [_key: BytesLike, _value: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBool"
  ): TypedContractMethod<
    [_key: BytesLike, _value: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBytes"
  ): TypedContractMethod<
    [_key: BytesLike, _value: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBytes32"
  ): TypedContractMethod<
    [_key: BytesLike, _value: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDeployedStatus"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGuardian"
  ): TypedContractMethod<[_newAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setInt"
  ): TypedContractMethod<
    [_key: BytesLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setString"
  ): TypedContractMethod<
    [_key: BytesLike, _value: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUint"
  ): TypedContractMethod<
    [_key: BytesLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWithdrawalAddress"
  ): TypedContractMethod<
    [
      _nodeAddress: AddressLike,
      _newWithdrawalAddress: AddressLike,
      _confirm: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subUint"
  ): TypedContractMethod<
    [_key: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GuardianChanged"
  ): TypedContractEvent<
    GuardianChangedEvent.InputTuple,
    GuardianChangedEvent.OutputTuple,
    GuardianChangedEvent.OutputObject
  >;
  getEvent(
    key: "NodeWithdrawalAddressSet"
  ): TypedContractEvent<
    NodeWithdrawalAddressSetEvent.InputTuple,
    NodeWithdrawalAddressSetEvent.OutputTuple,
    NodeWithdrawalAddressSetEvent.OutputObject
  >;

  filters: {
    "GuardianChanged(address,address)": TypedContractEvent<
      GuardianChangedEvent.InputTuple,
      GuardianChangedEvent.OutputTuple,
      GuardianChangedEvent.OutputObject
    >;
    GuardianChanged: TypedContractEvent<
      GuardianChangedEvent.InputTuple,
      GuardianChangedEvent.OutputTuple,
      GuardianChangedEvent.OutputObject
    >;

    "NodeWithdrawalAddressSet(address,address,uint256)": TypedContractEvent<
      NodeWithdrawalAddressSetEvent.InputTuple,
      NodeWithdrawalAddressSetEvent.OutputTuple,
      NodeWithdrawalAddressSetEvent.OutputObject
    >;
    NodeWithdrawalAddressSet: TypedContractEvent<
      NodeWithdrawalAddressSetEvent.InputTuple,
      NodeWithdrawalAddressSetEvent.OutputTuple,
      NodeWithdrawalAddressSetEvent.OutputObject
    >;
  };
}
