/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketDAONodeTrustedActionsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "actionChallengeDecide"
      | "actionChallengeMake"
      | "actionJoin"
      | "actionJoinRequired"
      | "actionKick"
      | "actionLeave"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActionChallengeDecided"
      | "ActionChallengeMade"
      | "ActionJoined"
      | "ActionKick"
      | "ActionLeave"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "actionChallengeDecide",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "actionChallengeMake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "actionJoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "actionJoinRequired",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "actionKick",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "actionLeave",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "actionChallengeDecide",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "actionChallengeMake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "actionJoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "actionJoinRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "actionKick", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "actionLeave",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace ActionChallengeDecidedEvent {
  export type InputTuple = [
    nodeChallengedAddress: AddressLike,
    nodeChallengeDeciderAddress: AddressLike,
    success: boolean,
    time: BigNumberish
  ];
  export type OutputTuple = [
    nodeChallengedAddress: string,
    nodeChallengeDeciderAddress: string,
    success: boolean,
    time: bigint
  ];
  export interface OutputObject {
    nodeChallengedAddress: string;
    nodeChallengeDeciderAddress: string;
    success: boolean;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionChallengeMadeEvent {
  export type InputTuple = [
    nodeChallengedAddress: AddressLike,
    nodeChallengerAddress: AddressLike,
    time: BigNumberish
  ];
  export type OutputTuple = [
    nodeChallengedAddress: string,
    nodeChallengerAddress: string,
    time: bigint
  ];
  export interface OutputObject {
    nodeChallengedAddress: string;
    nodeChallengerAddress: string;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionJoinedEvent {
  export type InputTuple = [
    nodeAddress: AddressLike,
    rplBondAmount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [
    nodeAddress: string,
    rplBondAmount: bigint,
    time: bigint
  ];
  export interface OutputObject {
    nodeAddress: string;
    rplBondAmount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionKickEvent {
  export type InputTuple = [
    nodeAddress: AddressLike,
    rplBondAmount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [
    nodeAddress: string,
    rplBondAmount: bigint,
    time: bigint
  ];
  export interface OutputObject {
    nodeAddress: string;
    rplBondAmount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionLeaveEvent {
  export type InputTuple = [
    nodeAddress: AddressLike,
    rplBondAmount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [
    nodeAddress: string,
    rplBondAmount: bigint,
    time: bigint
  ];
  export interface OutputObject {
    nodeAddress: string;
    rplBondAmount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RocketDAONodeTrustedActions extends BaseContract {
  connect(runner?: ContractRunner | null): RocketDAONodeTrustedActions;
  waitForDeployment(): Promise<this>;

  interface: RocketDAONodeTrustedActionsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  actionChallengeDecide: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  actionChallengeMake: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [void],
    "payable"
  >;

  actionJoin: TypedContractMethod<[], [void], "nonpayable">;

  actionJoinRequired: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  actionKick: TypedContractMethod<
    [_nodeAddress: AddressLike, _rplFine: BigNumberish],
    [void],
    "nonpayable"
  >;

  actionLeave: TypedContractMethod<
    [_rplBondRefundAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "actionChallengeDecide"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "actionChallengeMake"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "actionJoin"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "actionJoinRequired"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "actionKick"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _rplFine: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "actionLeave"
  ): TypedContractMethod<
    [_rplBondRefundAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ActionChallengeDecided"
  ): TypedContractEvent<
    ActionChallengeDecidedEvent.InputTuple,
    ActionChallengeDecidedEvent.OutputTuple,
    ActionChallengeDecidedEvent.OutputObject
  >;
  getEvent(
    key: "ActionChallengeMade"
  ): TypedContractEvent<
    ActionChallengeMadeEvent.InputTuple,
    ActionChallengeMadeEvent.OutputTuple,
    ActionChallengeMadeEvent.OutputObject
  >;
  getEvent(
    key: "ActionJoined"
  ): TypedContractEvent<
    ActionJoinedEvent.InputTuple,
    ActionJoinedEvent.OutputTuple,
    ActionJoinedEvent.OutputObject
  >;
  getEvent(
    key: "ActionKick"
  ): TypedContractEvent<
    ActionKickEvent.InputTuple,
    ActionKickEvent.OutputTuple,
    ActionKickEvent.OutputObject
  >;
  getEvent(
    key: "ActionLeave"
  ): TypedContractEvent<
    ActionLeaveEvent.InputTuple,
    ActionLeaveEvent.OutputTuple,
    ActionLeaveEvent.OutputObject
  >;

  filters: {
    "ActionChallengeDecided(address,address,bool,uint256)": TypedContractEvent<
      ActionChallengeDecidedEvent.InputTuple,
      ActionChallengeDecidedEvent.OutputTuple,
      ActionChallengeDecidedEvent.OutputObject
    >;
    ActionChallengeDecided: TypedContractEvent<
      ActionChallengeDecidedEvent.InputTuple,
      ActionChallengeDecidedEvent.OutputTuple,
      ActionChallengeDecidedEvent.OutputObject
    >;

    "ActionChallengeMade(address,address,uint256)": TypedContractEvent<
      ActionChallengeMadeEvent.InputTuple,
      ActionChallengeMadeEvent.OutputTuple,
      ActionChallengeMadeEvent.OutputObject
    >;
    ActionChallengeMade: TypedContractEvent<
      ActionChallengeMadeEvent.InputTuple,
      ActionChallengeMadeEvent.OutputTuple,
      ActionChallengeMadeEvent.OutputObject
    >;

    "ActionJoined(address,uint256,uint256)": TypedContractEvent<
      ActionJoinedEvent.InputTuple,
      ActionJoinedEvent.OutputTuple,
      ActionJoinedEvent.OutputObject
    >;
    ActionJoined: TypedContractEvent<
      ActionJoinedEvent.InputTuple,
      ActionJoinedEvent.OutputTuple,
      ActionJoinedEvent.OutputObject
    >;

    "ActionKick(address,uint256,uint256)": TypedContractEvent<
      ActionKickEvent.InputTuple,
      ActionKickEvent.OutputTuple,
      ActionKickEvent.OutputObject
    >;
    ActionKick: TypedContractEvent<
      ActionKickEvent.InputTuple,
      ActionKickEvent.OutputTuple,
      ActionKickEvent.OutputObject
    >;

    "ActionLeave(address,uint256,uint256)": TypedContractEvent<
      ActionLeaveEvent.InputTuple,
      ActionLeaveEvent.OutputTuple,
      ActionLeaveEvent.OutputObject
    >;
    ActionLeave: TypedContractEvent<
      ActionLeaveEvent.InputTuple,
      ActionLeaveEvent.OutputTuple,
      ActionLeaveEvent.OutputObject
    >;
  };
}
