/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketMerkleDistributorMainnetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claim"
      | "claimAndStake"
      | "claimOutstandingEth"
      | "getOutstandingEth"
      | "isClaimed"
      | "receiveVaultWithdrawalETH"
      | "relayRewards"
      | "version"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RewardsClaimed"): EventFragment;

  encodeFunctionData(
    functionFragment: "claim",
    values: [
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      BytesLike[][]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAndStake",
    values: [
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      BytesLike[][],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimOutstandingEth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOutstandingEth",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveVaultWithdrawalETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "relayRewards",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimAndStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimOutstandingEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutstandingEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isClaimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveVaultWithdrawalETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relayRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [
    claimer: AddressLike,
    rewardIndex: BigNumberish[],
    amountRPL: BigNumberish[],
    amountETH: BigNumberish[]
  ];
  export type OutputTuple = [
    claimer: string,
    rewardIndex: bigint[],
    amountRPL: bigint[],
    amountETH: bigint[]
  ];
  export interface OutputObject {
    claimer: string;
    rewardIndex: bigint[];
    amountRPL: bigint[];
    amountETH: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RocketMerkleDistributorMainnet extends BaseContract {
  connect(runner?: ContractRunner | null): RocketMerkleDistributorMainnet;
  waitForDeployment(): Promise<this>;

  interface: RocketMerkleDistributorMainnetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claim: TypedContractMethod<
    [
      _nodeAddress: AddressLike,
      _rewardIndex: BigNumberish[],
      _amountRPL: BigNumberish[],
      _amountETH: BigNumberish[],
      _merkleProof: BytesLike[][]
    ],
    [void],
    "nonpayable"
  >;

  claimAndStake: TypedContractMethod<
    [
      _nodeAddress: AddressLike,
      _rewardIndex: BigNumberish[],
      _amountRPL: BigNumberish[],
      _amountETH: BigNumberish[],
      _merkleProof: BytesLike[][],
      _stakeAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  claimOutstandingEth: TypedContractMethod<[], [void], "nonpayable">;

  getOutstandingEth: TypedContractMethod<
    [_address: AddressLike],
    [bigint],
    "view"
  >;

  isClaimed: TypedContractMethod<
    [_rewardIndex: BigNumberish, _claimer: AddressLike],
    [boolean],
    "view"
  >;

  receiveVaultWithdrawalETH: TypedContractMethod<[], [void], "payable">;

  relayRewards: TypedContractMethod<
    [
      _rewardIndex: BigNumberish,
      _root: BytesLike,
      _rewardsRPL: BigNumberish,
      _rewardsETH: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [
      _nodeAddress: AddressLike,
      _rewardIndex: BigNumberish[],
      _amountRPL: BigNumberish[],
      _amountETH: BigNumberish[],
      _merkleProof: BytesLike[][]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimAndStake"
  ): TypedContractMethod<
    [
      _nodeAddress: AddressLike,
      _rewardIndex: BigNumberish[],
      _amountRPL: BigNumberish[],
      _amountETH: BigNumberish[],
      _merkleProof: BytesLike[][],
      _stakeAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimOutstandingEth"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getOutstandingEth"
  ): TypedContractMethod<[_address: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isClaimed"
  ): TypedContractMethod<
    [_rewardIndex: BigNumberish, _claimer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiveVaultWithdrawalETH"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "relayRewards"
  ): TypedContractMethod<
    [
      _rewardIndex: BigNumberish,
      _root: BytesLike,
      _rewardsRPL: BigNumberish,
      _rewardsETH: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;

  filters: {
    "RewardsClaimed(address,uint256[],uint256[],uint256[])": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
  };
}
