/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketNodeStakingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "burnRPL"
      | "getNodeETHCollateralisationRatio"
      | "getNodeETHMatched"
      | "getNodeETHMatchedLimit"
      | "getNodeETHProvided"
      | "getNodeEffectiveRPLStake"
      | "getNodeMaximumRPLStake"
      | "getNodeMinimumRPLStake"
      | "getNodeRPLLocked"
      | "getNodeRPLStake"
      | "getNodeRPLStakedTime"
      | "getRPLLockingAllowed"
      | "getTotalRPLStake"
      | "lockRPL"
      | "setRPLLockingAllowed"
      | "setStakeRPLForAllowed(address,bool)"
      | "setStakeRPLForAllowed(address,address,bool)"
      | "slashRPL"
      | "stakeRPL"
      | "stakeRPLFor"
      | "transferRPL"
      | "unlockRPL"
      | "version"
      | "withdrawRPL(address,uint256)"
      | "withdrawRPL(uint256)"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RPLBurned"
      | "RPLLocked"
      | "RPLLockingAllowed"
      | "RPLSlashed"
      | "RPLStaked"
      | "RPLTransferred"
      | "RPLUnlocked"
      | "RPLWithdrawn"
      | "StakeRPLForAllowed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "burnRPL",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeETHCollateralisationRatio",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeETHMatched",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeETHMatchedLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeETHProvided",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeEffectiveRPLStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeMaximumRPLStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeMinimumRPLStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeRPLLocked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeRPLStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeRPLStakedTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRPLLockingAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRPLStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockRPL",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRPLLockingAllowed",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakeRPLForAllowed(address,bool)",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakeRPLForAllowed(address,address,bool)",
    values: [AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "slashRPL",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeRPL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeRPLFor",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferRPL",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockRPL",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawRPL(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRPL(uint256)",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "burnRPL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNodeETHCollateralisationRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeETHMatched",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeETHMatchedLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeETHProvided",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeEffectiveRPLStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeMaximumRPLStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeMinimumRPLStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeRPLLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeRPLStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeRPLStakedTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRPLLockingAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRPLStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockRPL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRPLLockingAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakeRPLForAllowed(address,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakeRPLForAllowed(address,address,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slashRPL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeRPL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeRPLFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferRPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlockRPL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRPL(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRPL(uint256)",
    data: BytesLike
  ): Result;
}

export namespace RPLBurnedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [from: string, amount: bigint, time: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLLockedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [from: string, amount: bigint, time: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLLockingAllowedEvent {
  export type InputTuple = [
    node: AddressLike,
    allowed: boolean,
    time: BigNumberish
  ];
  export type OutputTuple = [node: string, allowed: boolean, time: bigint];
  export interface OutputObject {
    node: string;
    allowed: boolean;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLSlashedEvent {
  export type InputTuple = [
    node: AddressLike,
    amount: BigNumberish,
    ethValue: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [
    node: string,
    amount: bigint,
    ethValue: bigint,
    time: bigint
  ];
  export interface OutputObject {
    node: string;
    amount: bigint;
    ethValue: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLStakedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [from: string, amount: bigint, time: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLTransferredEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    time: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLUnlockedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [from: string, amount: bigint, time: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RPLWithdrawnEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [to: string, amount: bigint, time: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeRPLForAllowedEvent {
  export type InputTuple = [
    node: AddressLike,
    caller: AddressLike,
    allowed: boolean,
    time: BigNumberish
  ];
  export type OutputTuple = [
    node: string,
    caller: string,
    allowed: boolean,
    time: bigint
  ];
  export interface OutputObject {
    node: string;
    caller: string;
    allowed: boolean;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RocketNodeStaking extends BaseContract {
  connect(runner?: ContractRunner | null): RocketNodeStaking;
  waitForDeployment(): Promise<this>;

  interface: RocketNodeStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  burnRPL: TypedContractMethod<
    [_from: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getNodeETHCollateralisationRatio: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeETHMatched: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeETHMatchedLimit: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeETHProvided: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeEffectiveRPLStake: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeMaximumRPLStake: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeMinimumRPLStake: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeRPLLocked: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeRPLStake: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNodeRPLStakedTime: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [bigint],
    "view"
  >;

  getRPLLockingAllowed: TypedContractMethod<
    [_nodeAddress: AddressLike],
    [boolean],
    "view"
  >;

  getTotalRPLStake: TypedContractMethod<[], [bigint], "view">;

  lockRPL: TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRPLLockingAllowed: TypedContractMethod<
    [_nodeAddress: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;

  "setStakeRPLForAllowed(address,bool)": TypedContractMethod<
    [_caller: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;

  "setStakeRPLForAllowed(address,address,bool)": TypedContractMethod<
    [_nodeAddress: AddressLike, _caller: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;

  slashRPL: TypedContractMethod<
    [_nodeAddress: AddressLike, _ethSlashAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeRPL: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  stakeRPLFor: TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferRPL: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unlockRPL: TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  "withdrawRPL(address,uint256)": TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  "withdrawRPL(uint256)": TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "burnRPL"
  ): TypedContractMethod<
    [_from: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getNodeETHCollateralisationRatio"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeETHMatched"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeETHMatchedLimit"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeETHProvided"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeEffectiveRPLStake"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeMaximumRPLStake"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeMinimumRPLStake"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeRPLLocked"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeRPLStake"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeRPLStakedTime"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRPLLockingAllowed"
  ): TypedContractMethod<[_nodeAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getTotalRPLStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockRPL"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRPLLockingAllowed"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStakeRPLForAllowed(address,bool)"
  ): TypedContractMethod<
    [_caller: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStakeRPLForAllowed(address,address,bool)"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _caller: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slashRPL"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _ethSlashAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeRPL"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeRPLFor"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferRPL"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockRPL"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawRPL(address,uint256)"
  ): TypedContractMethod<
    [_nodeAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawRPL(uint256)"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "RPLBurned"
  ): TypedContractEvent<
    RPLBurnedEvent.InputTuple,
    RPLBurnedEvent.OutputTuple,
    RPLBurnedEvent.OutputObject
  >;
  getEvent(
    key: "RPLLocked"
  ): TypedContractEvent<
    RPLLockedEvent.InputTuple,
    RPLLockedEvent.OutputTuple,
    RPLLockedEvent.OutputObject
  >;
  getEvent(
    key: "RPLLockingAllowed"
  ): TypedContractEvent<
    RPLLockingAllowedEvent.InputTuple,
    RPLLockingAllowedEvent.OutputTuple,
    RPLLockingAllowedEvent.OutputObject
  >;
  getEvent(
    key: "RPLSlashed"
  ): TypedContractEvent<
    RPLSlashedEvent.InputTuple,
    RPLSlashedEvent.OutputTuple,
    RPLSlashedEvent.OutputObject
  >;
  getEvent(
    key: "RPLStaked"
  ): TypedContractEvent<
    RPLStakedEvent.InputTuple,
    RPLStakedEvent.OutputTuple,
    RPLStakedEvent.OutputObject
  >;
  getEvent(
    key: "RPLTransferred"
  ): TypedContractEvent<
    RPLTransferredEvent.InputTuple,
    RPLTransferredEvent.OutputTuple,
    RPLTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RPLUnlocked"
  ): TypedContractEvent<
    RPLUnlockedEvent.InputTuple,
    RPLUnlockedEvent.OutputTuple,
    RPLUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "RPLWithdrawn"
  ): TypedContractEvent<
    RPLWithdrawnEvent.InputTuple,
    RPLWithdrawnEvent.OutputTuple,
    RPLWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "StakeRPLForAllowed"
  ): TypedContractEvent<
    StakeRPLForAllowedEvent.InputTuple,
    StakeRPLForAllowedEvent.OutputTuple,
    StakeRPLForAllowedEvent.OutputObject
  >;

  filters: {
    "RPLBurned(address,uint256,uint256)": TypedContractEvent<
      RPLBurnedEvent.InputTuple,
      RPLBurnedEvent.OutputTuple,
      RPLBurnedEvent.OutputObject
    >;
    RPLBurned: TypedContractEvent<
      RPLBurnedEvent.InputTuple,
      RPLBurnedEvent.OutputTuple,
      RPLBurnedEvent.OutputObject
    >;

    "RPLLocked(address,uint256,uint256)": TypedContractEvent<
      RPLLockedEvent.InputTuple,
      RPLLockedEvent.OutputTuple,
      RPLLockedEvent.OutputObject
    >;
    RPLLocked: TypedContractEvent<
      RPLLockedEvent.InputTuple,
      RPLLockedEvent.OutputTuple,
      RPLLockedEvent.OutputObject
    >;

    "RPLLockingAllowed(address,bool,uint256)": TypedContractEvent<
      RPLLockingAllowedEvent.InputTuple,
      RPLLockingAllowedEvent.OutputTuple,
      RPLLockingAllowedEvent.OutputObject
    >;
    RPLLockingAllowed: TypedContractEvent<
      RPLLockingAllowedEvent.InputTuple,
      RPLLockingAllowedEvent.OutputTuple,
      RPLLockingAllowedEvent.OutputObject
    >;

    "RPLSlashed(address,uint256,uint256,uint256)": TypedContractEvent<
      RPLSlashedEvent.InputTuple,
      RPLSlashedEvent.OutputTuple,
      RPLSlashedEvent.OutputObject
    >;
    RPLSlashed: TypedContractEvent<
      RPLSlashedEvent.InputTuple,
      RPLSlashedEvent.OutputTuple,
      RPLSlashedEvent.OutputObject
    >;

    "RPLStaked(address,uint256,uint256)": TypedContractEvent<
      RPLStakedEvent.InputTuple,
      RPLStakedEvent.OutputTuple,
      RPLStakedEvent.OutputObject
    >;
    RPLStaked: TypedContractEvent<
      RPLStakedEvent.InputTuple,
      RPLStakedEvent.OutputTuple,
      RPLStakedEvent.OutputObject
    >;

    "RPLTransferred(address,address,uint256,uint256)": TypedContractEvent<
      RPLTransferredEvent.InputTuple,
      RPLTransferredEvent.OutputTuple,
      RPLTransferredEvent.OutputObject
    >;
    RPLTransferred: TypedContractEvent<
      RPLTransferredEvent.InputTuple,
      RPLTransferredEvent.OutputTuple,
      RPLTransferredEvent.OutputObject
    >;

    "RPLUnlocked(address,uint256,uint256)": TypedContractEvent<
      RPLUnlockedEvent.InputTuple,
      RPLUnlockedEvent.OutputTuple,
      RPLUnlockedEvent.OutputObject
    >;
    RPLUnlocked: TypedContractEvent<
      RPLUnlockedEvent.InputTuple,
      RPLUnlockedEvent.OutputTuple,
      RPLUnlockedEvent.OutputObject
    >;

    "RPLWithdrawn(address,uint256,uint256)": TypedContractEvent<
      RPLWithdrawnEvent.InputTuple,
      RPLWithdrawnEvent.OutputTuple,
      RPLWithdrawnEvent.OutputObject
    >;
    RPLWithdrawn: TypedContractEvent<
      RPLWithdrawnEvent.InputTuple,
      RPLWithdrawnEvent.OutputTuple,
      RPLWithdrawnEvent.OutputObject
    >;

    "StakeRPLForAllowed(address,address,bool,uint256)": TypedContractEvent<
      StakeRPLForAllowedEvent.InputTuple,
      StakeRPLForAllowedEvent.OutputTuple,
      StakeRPLForAllowedEvent.OutputObject
    >;
    StakeRPLForAllowed: TypedContractEvent<
      StakeRPLForAllowedEvent.InputTuple,
      StakeRPLForAllowedEvent.OutputTuple,
      StakeRPLForAllowedEvent.OutputObject
    >;
  };
}
