/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketNetworkPenaltiesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "executeUpdatePenalty"
      | "getPenaltyCount"
      | "submitPenalty"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PenaltySubmitted" | "PenaltyUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "executeUpdatePenalty",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPenaltyCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPenalty",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "executeUpdatePenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPenaltyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace PenaltySubmittedEvent {
  export type InputTuple = [
    from: AddressLike,
    minipoolAddress: AddressLike,
    block: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    minipoolAddress: string,
    block: bigint,
    time: bigint
  ];
  export interface OutputObject {
    from: string;
    minipoolAddress: string;
    block: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PenaltyUpdatedEvent {
  export type InputTuple = [
    minipoolAddress: AddressLike,
    penalty: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [
    minipoolAddress: string,
    penalty: bigint,
    time: bigint
  ];
  export interface OutputObject {
    minipoolAddress: string;
    penalty: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RocketNetworkPenalties extends BaseContract {
  connect(runner?: ContractRunner | null): RocketNetworkPenalties;
  waitForDeployment(): Promise<this>;

  interface: RocketNetworkPenaltiesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeUpdatePenalty: TypedContractMethod<
    [_minipoolAddress: AddressLike, _block: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPenaltyCount: TypedContractMethod<
    [_minipoolAddress: AddressLike],
    [bigint],
    "view"
  >;

  submitPenalty: TypedContractMethod<
    [_minipoolAddress: AddressLike, _block: BigNumberish],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeUpdatePenalty"
  ): TypedContractMethod<
    [_minipoolAddress: AddressLike, _block: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPenaltyCount"
  ): TypedContractMethod<[_minipoolAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitPenalty"
  ): TypedContractMethod<
    [_minipoolAddress: AddressLike, _block: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "PenaltySubmitted"
  ): TypedContractEvent<
    PenaltySubmittedEvent.InputTuple,
    PenaltySubmittedEvent.OutputTuple,
    PenaltySubmittedEvent.OutputObject
  >;
  getEvent(
    key: "PenaltyUpdated"
  ): TypedContractEvent<
    PenaltyUpdatedEvent.InputTuple,
    PenaltyUpdatedEvent.OutputTuple,
    PenaltyUpdatedEvent.OutputObject
  >;

  filters: {
    "PenaltySubmitted(address,address,uint256,uint256)": TypedContractEvent<
      PenaltySubmittedEvent.InputTuple,
      PenaltySubmittedEvent.OutputTuple,
      PenaltySubmittedEvent.OutputObject
    >;
    PenaltySubmitted: TypedContractEvent<
      PenaltySubmittedEvent.InputTuple,
      PenaltySubmittedEvent.OutputTuple,
      PenaltySubmittedEvent.OutputObject
    >;

    "PenaltyUpdated(address,uint256,uint256)": TypedContractEvent<
      PenaltyUpdatedEvent.InputTuple,
      PenaltyUpdatedEvent.OutputTuple,
      PenaltyUpdatedEvent.OutputObject
    >;
    PenaltyUpdated: TypedContractEvent<
      PenaltyUpdatedEvent.InputTuple,
      PenaltyUpdatedEvent.OutputTuple,
      PenaltyUpdatedEvent.OutputObject
    >;
  };
}
