/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketDAONodeTrustedSettingsMinipoolInterface
  extends Interface {
  getFunction(
    nameOrSignature:
      | "getBondReductionWindowLength"
      | "getBondReductionWindowStart"
      | "getCancelBondReductionQuorum"
      | "getPromotionScrubPeriod"
      | "getScrubPenaltyEnabled"
      | "getScrubPeriod"
      | "getScrubQuorum"
      | "getSettingBool"
      | "getSettingUint"
      | "isWithinBondReductionWindow"
      | "setSettingBool"
      | "setSettingUint"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getBondReductionWindowLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBondReductionWindowStart",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCancelBondReductionQuorum",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPromotionScrubPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getScrubPenaltyEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getScrubPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getScrubQuorum",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSettingBool",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSettingUint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isWithinBondReductionWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettingBool",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettingUint",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getBondReductionWindowLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBondReductionWindowStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCancelBondReductionQuorum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPromotionScrubPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScrubPenaltyEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScrubPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScrubQuorum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettingBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettingUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWithinBondReductionWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettingBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettingUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export interface RocketDAONodeTrustedSettingsMinipool extends BaseContract {
  connect(runner?: ContractRunner | null): RocketDAONodeTrustedSettingsMinipool;
  waitForDeployment(): Promise<this>;

  interface: RocketDAONodeTrustedSettingsMinipoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBondReductionWindowLength: TypedContractMethod<[], [bigint], "view">;

  getBondReductionWindowStart: TypedContractMethod<[], [bigint], "view">;

  getCancelBondReductionQuorum: TypedContractMethod<[], [bigint], "view">;

  getPromotionScrubPeriod: TypedContractMethod<[], [bigint], "view">;

  getScrubPenaltyEnabled: TypedContractMethod<[], [boolean], "view">;

  getScrubPeriod: TypedContractMethod<[], [bigint], "view">;

  getScrubQuorum: TypedContractMethod<[], [bigint], "view">;

  getSettingBool: TypedContractMethod<
    [_settingPath: string],
    [boolean],
    "view"
  >;

  getSettingUint: TypedContractMethod<[_settingPath: string], [bigint], "view">;

  isWithinBondReductionWindow: TypedContractMethod<
    [_time: BigNumberish],
    [boolean],
    "view"
  >;

  setSettingBool: TypedContractMethod<
    [_settingPath: string, _value: boolean],
    [void],
    "nonpayable"
  >;

  setSettingUint: TypedContractMethod<
    [_settingPath: string, _value: BigNumberish],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBondReductionWindowLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBondReductionWindowStart"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCancelBondReductionQuorum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPromotionScrubPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getScrubPenaltyEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getScrubPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getScrubQuorum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSettingBool"
  ): TypedContractMethod<[_settingPath: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "getSettingUint"
  ): TypedContractMethod<[_settingPath: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "isWithinBondReductionWindow"
  ): TypedContractMethod<[_time: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "setSettingBool"
  ): TypedContractMethod<
    [_settingPath: string, _value: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettingUint"
  ): TypedContractMethod<
    [_settingPath: string, _value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
