/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketDAOSecurityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getMemberAt"
      | "getMemberCount"
      | "getMemberID"
      | "getMemberIsValid"
      | "getMemberJoinedTime"
      | "getMemberProposalExecutedTime"
      | "getMemberQuorumVotesRequired"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMemberAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberID",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberIsValid",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberJoinedTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberProposalExecutedTime",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberQuorumVotesRequired",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getMemberAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberIsValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberJoinedTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberProposalExecutedTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberQuorumVotesRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export interface RocketDAOSecurity extends BaseContract {
  connect(runner?: ContractRunner | null): RocketDAOSecurity;
  waitForDeployment(): Promise<this>;

  interface: RocketDAOSecurityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMemberAt: TypedContractMethod<[_index: BigNumberish], [string], "view">;

  getMemberCount: TypedContractMethod<[], [bigint], "view">;

  getMemberID: TypedContractMethod<
    [_memberAddress: AddressLike],
    [string],
    "view"
  >;

  getMemberIsValid: TypedContractMethod<
    [_memberAddress: AddressLike],
    [boolean],
    "view"
  >;

  getMemberJoinedTime: TypedContractMethod<
    [_memberAddress: AddressLike],
    [bigint],
    "view"
  >;

  getMemberProposalExecutedTime: TypedContractMethod<
    [_proposalType: string, _memberAddress: AddressLike],
    [bigint],
    "view"
  >;

  getMemberQuorumVotesRequired: TypedContractMethod<[], [bigint], "view">;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMemberAt"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getMemberCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMemberID"
  ): TypedContractMethod<[_memberAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getMemberIsValid"
  ): TypedContractMethod<[_memberAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getMemberJoinedTime"
  ): TypedContractMethod<[_memberAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMemberProposalExecutedTime"
  ): TypedContractMethod<
    [_proposalType: string, _memberAddress: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMemberQuorumVotesRequired"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
