/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RocketNetworkBalancesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "executeUpdateBalances"
      | "getBalancesBlock"
      | "getETHUtilizationRate"
      | "getStakingETHBalance"
      | "getTotalETHBalance"
      | "getTotalRETHSupply"
      | "submitBalances"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BalancesSubmitted" | "BalancesUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "executeUpdateBalances",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalancesBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getETHUtilizationRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStakingETHBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalETHBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRETHSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitBalances",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "executeUpdateBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalancesBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getETHUtilizationRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakingETHBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalETHBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRETHSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace BalancesSubmittedEvent {
  export type InputTuple = [
    from: AddressLike,
    block: BigNumberish,
    slotTimestamp: BigNumberish,
    totalEth: BigNumberish,
    stakingEth: BigNumberish,
    rethSupply: BigNumberish,
    blockTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    block: bigint,
    slotTimestamp: bigint,
    totalEth: bigint,
    stakingEth: bigint,
    rethSupply: bigint,
    blockTimestamp: bigint
  ];
  export interface OutputObject {
    from: string;
    block: bigint;
    slotTimestamp: bigint;
    totalEth: bigint;
    stakingEth: bigint;
    rethSupply: bigint;
    blockTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BalancesUpdatedEvent {
  export type InputTuple = [
    block: BigNumberish,
    slotTimestamp: BigNumberish,
    totalEth: BigNumberish,
    stakingEth: BigNumberish,
    rethSupply: BigNumberish,
    blockTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    block: bigint,
    slotTimestamp: bigint,
    totalEth: bigint,
    stakingEth: bigint,
    rethSupply: bigint,
    blockTimestamp: bigint
  ];
  export interface OutputObject {
    block: bigint;
    slotTimestamp: bigint;
    totalEth: bigint;
    stakingEth: bigint;
    rethSupply: bigint;
    blockTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RocketNetworkBalances extends BaseContract {
  connect(runner?: ContractRunner | null): RocketNetworkBalances;
  waitForDeployment(): Promise<this>;

  interface: RocketNetworkBalancesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeUpdateBalances: TypedContractMethod<
    [
      _block: BigNumberish,
      _slotTimestamp: BigNumberish,
      _totalEth: BigNumberish,
      _stakingEth: BigNumberish,
      _rethSupply: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getBalancesBlock: TypedContractMethod<[], [bigint], "view">;

  getETHUtilizationRate: TypedContractMethod<[], [bigint], "view">;

  getStakingETHBalance: TypedContractMethod<[], [bigint], "view">;

  getTotalETHBalance: TypedContractMethod<[], [bigint], "view">;

  getTotalRETHSupply: TypedContractMethod<[], [bigint], "view">;

  submitBalances: TypedContractMethod<
    [
      _block: BigNumberish,
      _slotTimestamp: BigNumberish,
      _totalEth: BigNumberish,
      _stakingEth: BigNumberish,
      _rethSupply: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeUpdateBalances"
  ): TypedContractMethod<
    [
      _block: BigNumberish,
      _slotTimestamp: BigNumberish,
      _totalEth: BigNumberish,
      _stakingEth: BigNumberish,
      _rethSupply: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalancesBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getETHUtilizationRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStakingETHBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalETHBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalRETHSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitBalances"
  ): TypedContractMethod<
    [
      _block: BigNumberish,
      _slotTimestamp: BigNumberish,
      _totalEth: BigNumberish,
      _stakingEth: BigNumberish,
      _rethSupply: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "BalancesSubmitted"
  ): TypedContractEvent<
    BalancesSubmittedEvent.InputTuple,
    BalancesSubmittedEvent.OutputTuple,
    BalancesSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "BalancesUpdated"
  ): TypedContractEvent<
    BalancesUpdatedEvent.InputTuple,
    BalancesUpdatedEvent.OutputTuple,
    BalancesUpdatedEvent.OutputObject
  >;

  filters: {
    "BalancesSubmitted(address,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      BalancesSubmittedEvent.InputTuple,
      BalancesSubmittedEvent.OutputTuple,
      BalancesSubmittedEvent.OutputObject
    >;
    BalancesSubmitted: TypedContractEvent<
      BalancesSubmittedEvent.InputTuple,
      BalancesSubmittedEvent.OutputTuple,
      BalancesSubmittedEvent.OutputObject
    >;

    "BalancesUpdated(uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      BalancesUpdatedEvent.InputTuple,
      BalancesUpdatedEvent.OutputTuple,
      BalancesUpdatedEvent.OutputObject
    >;
    BalancesUpdated: TypedContractEvent<
      BalancesUpdatedEvent.InputTuple,
      BalancesUpdatedEvent.OutputTuple,
      BalancesUpdatedEvent.OutputObject
    >;
  };
}
