/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RocketSmoothingPoolInterface extends Interface {
  getFunction(nameOrSignature: "version" | "withdrawEther"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EtherWithdrawn"): EventFragment;

  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawEther",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEther",
    data: BytesLike
  ): Result;
}

export namespace EtherWithdrawnEvent {
  export type InputTuple = [
    by: string,
    to: AddressLike,
    amount: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [
    by: string,
    to: string,
    amount: bigint,
    time: bigint
  ];
  export interface OutputObject {
    by: string;
    to: string;
    amount: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RocketSmoothingPool extends BaseContract {
  connect(runner?: ContractRunner | null): RocketSmoothingPool;
  waitForDeployment(): Promise<this>;

  interface: RocketSmoothingPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  version: TypedContractMethod<[], [bigint], "view">;

  withdrawEther: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawEther"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EtherWithdrawn"
  ): TypedContractEvent<
    EtherWithdrawnEvent.InputTuple,
    EtherWithdrawnEvent.OutputTuple,
    EtherWithdrawnEvent.OutputObject
  >;

  filters: {
    "EtherWithdrawn(string,address,uint256,uint256)": TypedContractEvent<
      EtherWithdrawnEvent.InputTuple,
      EtherWithdrawnEvent.OutputTuple,
      EtherWithdrawnEvent.OutputObject
    >;
    EtherWithdrawn: TypedContractEvent<
      EtherWithdrawnEvent.InputTuple,
      EtherWithdrawnEvent.OutputTuple,
      EtherWithdrawnEvent.OutputObject
    >;
  };
}
