/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StorageHelperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addUint"
      | "deleteAddress"
      | "deleteBool"
      | "deleteBytes"
      | "deleteBytes32"
      | "deleteInt"
      | "deleteString"
      | "deleteUint"
      | "getAddress"
      | "getBool"
      | "getBytes"
      | "getBytes32"
      | "getInt"
      | "getString"
      | "getUint"
      | "rocketStorage"
      | "setAddress"
      | "setBool"
      | "setBytes"
      | "setBytes32"
      | "setInt"
      | "setString"
      | "setUint"
      | "subUint"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addUint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBool",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBytes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBytes32",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteInt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteUint",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getBool", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getBytes", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getBytes32",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getInt", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getUint", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "rocketStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBool",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes32",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setInt",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setString",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setUint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subUint",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteBool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteBytes32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteInt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteUint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBytes32", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getInt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getString", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rocketStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBytes32", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setInt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setString", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subUint", data: BytesLike): Result;
}

export interface StorageHelper extends BaseContract {
  connect(runner?: ContractRunner | null): StorageHelper;
  waitForDeployment(): Promise<this>;

  interface: StorageHelperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addUint: TypedContractMethod<
    [_key: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  deleteAddress: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  deleteBool: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  deleteBytes: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  deleteBytes32: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  deleteInt: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  deleteString: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  deleteUint: TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;

  getAddress: TypedContractMethod<[_key: BytesLike], [string], "view">;

  getBool: TypedContractMethod<[_key: BytesLike], [boolean], "view">;

  getBytes: TypedContractMethod<[_key: BytesLike], [string], "view">;

  getBytes32: TypedContractMethod<[_key: BytesLike], [string], "view">;

  getInt: TypedContractMethod<[_key: BytesLike], [bigint], "view">;

  getString: TypedContractMethod<[_key: BytesLike], [string], "view">;

  getUint: TypedContractMethod<[_key: BytesLike], [bigint], "view">;

  rocketStorage: TypedContractMethod<[], [string], "view">;

  setAddress: TypedContractMethod<
    [_key: BytesLike, _value: AddressLike],
    [void],
    "nonpayable"
  >;

  setBool: TypedContractMethod<
    [_key: BytesLike, _value: boolean],
    [void],
    "nonpayable"
  >;

  setBytes: TypedContractMethod<
    [_key: BytesLike, _value: BytesLike],
    [void],
    "nonpayable"
  >;

  setBytes32: TypedContractMethod<
    [_key: BytesLike, _value: BytesLike],
    [void],
    "nonpayable"
  >;

  setInt: TypedContractMethod<
    [_key: BytesLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;

  setString: TypedContractMethod<
    [_key: BytesLike, _value: string],
    [void],
    "nonpayable"
  >;

  setUint: TypedContractMethod<
    [_key: BytesLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;

  subUint: TypedContractMethod<
    [_key: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addUint"
  ): TypedContractMethod<
    [_key: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteAddress"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteBool"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteBytes"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteBytes32"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteInt"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteString"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteUint"
  ): TypedContractMethod<[_key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<[_key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getBool"
  ): TypedContractMethod<[_key: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBytes"
  ): TypedContractMethod<[_key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getBytes32"
  ): TypedContractMethod<[_key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getInt"
  ): TypedContractMethod<[_key: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getString"
  ): TypedContractMethod<[_key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUint"
  ): TypedContractMethod<[_key: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "rocketStorage"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAddress"
  ): TypedContractMethod<
    [_key: BytesLike, _value: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBool"
  ): TypedContractMethod<
    [_key: BytesLike, _value: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBytes"
  ): TypedContractMethod<
    [_key: BytesLike, _value: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBytes32"
  ): TypedContractMethod<
    [_key: BytesLike, _value: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setInt"
  ): TypedContractMethod<
    [_key: BytesLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setString"
  ): TypedContractMethod<
    [_key: BytesLike, _value: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUint"
  ): TypedContractMethod<
    [_key: BytesLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subUint"
  ): TypedContractMethod<
    [_key: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
