name: CI
on: [push]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install Components
        run: npm ci

      - name: Run Rocket Pool tests
        run: npm test
